/*
 * Registry runtime Fase A per Motore Generico NEXT.
 *
 * Fonte umana: docs/product/REGISTRO_COLLECTION_FIRESTORE.md v0.6 BOZZA.
 * Quando il registro cambia, aggiornare manualmente questo file.
 * Decisione 2026-05-04, scelta B: il registro Markdown resta fonte umana;
 * questa configurazione CommonJS e' la fonte runtime derivata.
 *
 * Fase A copre entry exact_document necessarie alla parita' Driver360 e
 * ai primi moduli prioritari del motore generico.
 * Convenzione chiavi: <domain>.<datasetCamelCase>, es. driver360.colleghi.
 */

export const REGISTRY_CONFIG_FASE_A = Object.freeze({
  version: "registry.config.faseA.v0.1",
  generatedFrom: "REGISTRO_COLLECTION_FIRESTORE.md v0.6 BOZZA + internal-ai-firebase-readonly-boundary.js",
  entries: Object.freeze({
    "driver360.colleghi": Object.freeze({
      key: "driver360.colleghi",
      boundaryEntryId: "firestore-storage-colleghi-doc",
      datasetKey: "@colleghi",
      accessMode: "exact_document",
      collection: "storage",
      docId: "@colleghi",
      sourceOfTruth: "registry v0.6 BOZZA + boundary firestore-storage-colleghi-doc",
      matchStrategy: "driver_name_or_badge_exact_token_match",
      allowedFields: Object.freeze([
        "id",
        "nome",
        "nomeCompleto",
        "label",
        "badge",
        "codice",
      ]),
      forbiddenFields: Object.freeze([
        "descrizione",
        "note",
        "telefono",
        "telefonoPrivato",
        "pinSim",
        "pukSim",
        "schedeCarburante",
      ]),
      aliases: Object.freeze({
        autista: Object.freeze({
          id: Object.freeze(["id"]),
          displayName: Object.freeze(["nome", "nomeCompleto", "label"]),
          badge: Object.freeze(["badge"]),
          codice: Object.freeze(["codice"]),
        }),
      }),
      requestLimits: Object.freeze({
        maxDocumentReadsPerRequest: 1,
        maxReturnedVehicleRecords: 20,
      }),
    }),
    // Boundary: internal-ai-firebase-readonly-boundary.js:726-752.
    "sessions.autistiSessioneAttive": Object.freeze({
      key: "sessions.autistiSessioneAttive",
      boundaryEntryId: "firestore-storage-autisti-sessioni-attive-doc",
      datasetKey: "@autisti_sessione_attive",
      accessMode: "exact_document",
      collection: "storage",
      docId: "@autisti_sessione_attive",
      sourceOfTruth: "registry v0.6 BOZZA + boundary firestore-storage-autisti-sessioni-attive-doc",
      matchStrategy: "driver_badge_or_id_and_plate_exact_match",
      allowedFields: Object.freeze([
        "id",
        "autistaId",
        "nomeAutista",
        "autistaNome",
        "autista",
        "badgeAutista",
        "badge",
        "mezzoTarga",
        "targaMotrice",
        "targaRimorchio",
        "targa",
        "statoSessione",
        "stato",
        "sessione",
        "timestamp",
      ]),
      forbiddenFields: Object.freeze([
        "note",
        "descrizione",
        "messaggio",
        "dettaglio",
        "fotoUrl",
        "fotoUrls",
      ]),
      aliases: Object.freeze({
        autista: Object.freeze({
          id: Object.freeze(["autistaId"]),
          displayName: Object.freeze(["nomeAutista", "autistaNome", "autista"]),
          badge: Object.freeze(["badgeAutista", "badge"]),
        }),
        mezzo: Object.freeze({
          targa: Object.freeze(["mezzoTarga", "targaMotrice", "targaRimorchio", "targa"]),
        }),
        sessioneAttiva: Object.freeze({
          badge: Object.freeze(["badgeAutista"]),
          targaMotrice: Object.freeze(["targaMotrice"]),
          targaRimorchio: Object.freeze(["targaRimorchio"]),
          timestamp: Object.freeze(["timestamp"]),
        }),
      }),
      requestLimits: Object.freeze({
        maxDocumentReadsPerRequest: 1,
        maxReturnedVehicleRecords: 20,
      }),
    }),
    // Boundary: internal-ai-firebase-readonly-boundary.js:667-684.
    "vehicles.mezziAziendali": Object.freeze({
      key: "vehicles.mezziAziendali",
      boundaryEntryId: "firestore-storage-mezzi-aziendali-doc",
      datasetKey: "@mezzi_aziendali",
      accessMode: "exact_document",
      collection: "storage",
      docId: "@mezzi_aziendali",
      sourceOfTruth:
        "registry v0.6 BOZZA + boundary firestore-storage-mezzi-aziendali-doc (post C-FIX 2026-05-04)",
      matchStrategy: "single_targa_exact_match",
      allowedFields: Object.freeze([
        "id",
        "targa",
        "categoria",
        "marca",
        "modello",
        "autistaId",
        "autistaNome",
        "librettoStoragePath",
        "dataImmatricolazione",
        "dataScadenzaRevisione",
        "dataUltimoCollaudo",
        "fotoPath",
        "telaio",
        "massaComplessiva",
      ]),
      forbiddenFields: Object.freeze([]),
      aliases: Object.freeze({
        mezzo: Object.freeze({
          id: Object.freeze(["id"]),
          targa: Object.freeze(["targa"]),
          categoria: Object.freeze(["categoria"]),
          marca: Object.freeze(["marca"]),
          modello: Object.freeze(["modello"]),
          telaio: Object.freeze(["telaio"]),
        }),
        autista: Object.freeze({
          id: Object.freeze(["autistaId"]),
          displayName: Object.freeze(["autistaNome"]),
        }),
        documento: Object.freeze({
          librettoPath: Object.freeze(["librettoStoragePath"]),
          fotoPath: Object.freeze(["fotoPath"]),
        }),
      }),
      requestLimits: Object.freeze({
        maxDocumentReadsPerRequest: 1,
        maxReturnedVehicleRecords: 1,
      }),
    }),
    // Boundary: internal-ai-firebase-readonly-boundary.js:787-814.
    "refuelings.rifornimentiAutistiTmp": Object.freeze({
      key: "refuelings.rifornimentiAutistiTmp",
      boundaryEntryId: "firestore-storage-rifornimenti-autisti-tmp-doc",
      datasetKey: "@rifornimenti_autisti_tmp",
      accessMode: "exact_document",
      collection: "storage",
      docId: "@rifornimenti_autisti_tmp",
      sourceOfTruth: "registry v0.6 BOZZA + boundary firestore-storage-rifornimenti-autisti-tmp-doc",
      matchStrategy: "driver_id_and_plate_exact_match",
      allowedFields: Object.freeze([
        "id",
        "originId",
        "autistaId",
        "badgeAutista",
        "badge",
        "mezzoTarga",
        "targa",
        "targaMotrice",
        "timestamp",
        "data",
        "litri",
        "km",
        "confermatoAutista",
      ]),
      forbiddenFields: Object.freeze([
        "note",
        "descrizione",
        "messaggio",
        "distributore",
        "fornitore",
        "importo",
        "costo",
      ]),
      aliases: Object.freeze({
        rifornimento: Object.freeze({
          id: Object.freeze(["id", "originId"]),
          data: Object.freeze(["data", "timestamp"]),
          quantita: Object.freeze(["litri"]),
          km: Object.freeze(["km"]),
        }),
        autista: Object.freeze({
          id: Object.freeze(["autistaId"]),
          badge: Object.freeze(["badgeAutista", "badge"]),
        }),
        mezzo: Object.freeze({
          targa: Object.freeze(["mezzoTarga", "targa", "targaMotrice"]),
        }),
      }),
      requestLimits: Object.freeze({
        maxDocumentReadsPerRequest: 1,
        maxReturnedVehicleRecords: 20,
      }),
    }),
    // Boundary: internal-ai-firebase-readonly-boundary.js:1230-1246.
    "refuelings.rifornimenti": Object.freeze({
      key: "refuelings.rifornimenti",
      boundaryEntryId: "firestore-storage-rifornimenti-doc",
      datasetKey: "@rifornimenti",
      accessMode: "exact_document",
      collection: "storage",
      docId: "@rifornimenti",
      sourceOfTruth: "registry v0.6 BOZZA + boundary firestore-storage-rifornimenti-doc",
      matchStrategy: "vehicle_plate_exact_match",
      allowedFields: Object.freeze([
        "id",
        "targa",
        "mezzoTarga",
        "targaMotrice",
        "autistaId",
        "badgeAutista",
        "data",
        "timestamp",
        "litri",
        "km",
        "costo",
        "distributore",
        "sourceRecordId",
      ]),
      forbiddenFields: Object.freeze([
        "note",
        "descrizione",
        "messaggio",
        "commento",
        "testo",
        "dettaglio",
        "rawText",
        "extractedText",
        "riepilogoBreve",
        "analisiCosti",
        "anomalie",
        "fornitoriNotevoli",
        "apiKey",
        "token",
        "password",
        "secret",
        "telefono",
        "telefonoPrivato",
        "telefoniAggiuntivi",
        "email",
        "indirizzo",
        "pinSim",
        "pukSim",
        "schedeCarburante",
        "downloadUrl",
        "fileUrl",
        "pdfUrl",
        "url",
        "imageUrls",
        "fotoUrl",
        "fornitore",
        "importo",
      ]),
      aliases: Object.freeze({
        rifornimento: Object.freeze({
          id: Object.freeze(["id", "sourceRecordId"]),
          data: Object.freeze(["data", "timestamp"]),
          quantita: Object.freeze(["litri"]),
          km: Object.freeze(["km"]),
          costo: Object.freeze(["costo"]),
          distributore: Object.freeze(["distributore"]),
        }),
        autista: Object.freeze({
          id: Object.freeze(["autistaId"]),
          badge: Object.freeze(["badgeAutista"]),
        }),
        mezzo: Object.freeze({
          targa: Object.freeze(["targa", "mezzoTarga", "targaMotrice"]),
        }),
      }),
      requestLimits: Object.freeze({
        maxDocumentReadsPerRequest: 1,
        maxReturnedVehicleRecords: 100,
      }),
    }),
  }),
});
