/*
 * Registry runtime Fase A per Motore Generico NEXT.
 *
 * Fonte umana: docs/product/REGISTRO_COLLECTION_FIRESTORE.md v0.6 BOZZA.
 * Quando il registro cambia, aggiornare manualmente questo file.
 * Decisione 2026-05-04, scelta B: il registro Markdown resta fonte umana;
 * questa configurazione CommonJS e' la fonte runtime derivata.
 *
 * Fase A copre entry exact_document necessarie alla parita' Driver360 e
 * ai primi moduli prioritari del motore generico.
 * Convenzione chiavi: <domain>.<datasetCamelCase>, es. driver360.colleghi.
 */

export const REGISTRY_CONFIG_FASE_A = Object.freeze({
  version: "registry.config.faseA.v0.1",
  generatedFrom: "REGISTRO_COLLECTION_FIRESTORE.md v0.6 BOZZA + internal-ai-firebase-readonly-boundary.js",
  entries: Object.freeze({
    "driver360.colleghi": Object.freeze({
      key: "driver360.colleghi",
      boundaryEntryId: "firestore-storage-colleghi-doc",
      datasetKey: "@colleghi",
      accessMode: "exact_document",
      collection: "storage",
      docId: "@colleghi",
      sourceOfTruth: "registry v0.6 BOZZA + boundary firestore-storage-colleghi-doc",
      matchStrategy: "driver_name_or_badge_exact_token_match",
      viewBindings: Object.freeze(["Driver360"]),
      allowedFields: Object.freeze([
        "id",
        "nome",
        "nomeCompleto",
        "label",
        "badge",
        "codice",
      ]),
      forbiddenFields: Object.freeze([
        "descrizione",
        "note",
        "telefono",
        "telefonoPrivato",
        "pinSim",
        "pukSim",
        "schedeCarburante",
      ]),
      aliases: Object.freeze({
        autista: Object.freeze({
          id: Object.freeze(["id"]),
          displayName: Object.freeze(["nome", "nomeCompleto", "label"]),
          badge: Object.freeze(["badge"]),
          codice: Object.freeze(["codice"]),
        }),
      }),
      requestLimits: Object.freeze({
        maxDocumentReadsPerRequest: 1,
        maxReturnedVehicleRecords: 20,
      }),
    }),
    // Boundary: internal-ai-firebase-readonly-boundary.js:726-752.
    "sessions.autistiSessioneAttive": Object.freeze({
      key: "sessions.autistiSessioneAttive",
      boundaryEntryId: "firestore-storage-autisti-sessioni-attive-doc",
      datasetKey: "@autisti_sessione_attive",
      accessMode: "exact_document",
      collection: "storage",
      docId: "@autisti_sessione_attive",
      sourceOfTruth: "registry v0.6 BOZZA + boundary firestore-storage-autisti-sessioni-attive-doc",
      matchStrategy: "driver_badge_or_id_and_plate_exact_match",
      viewBindings: Object.freeze(["Driver360", "Vehicle360"]),
      allowedFields: Object.freeze([
        "id",
        "autistaId",
        "nomeAutista",
        "autistaNome",
        "autista",
        "badgeAutista",
        "badge",
        "mezzoTarga",
        "targaMotrice",
        "targaRimorchio",
        "targa",
        "statoSessione",
        "stato",
        "sessione",
        "timestamp",
      ]),
      forbiddenFields: Object.freeze([
        "note",
        "descrizione",
        "messaggio",
        "dettaglio",
        "fotoUrl",
        "fotoUrls",
      ]),
      aliases: Object.freeze({
        autista: Object.freeze({
          id: Object.freeze(["autistaId"]),
          displayName: Object.freeze(["nomeAutista", "autistaNome", "autista"]),
          badge: Object.freeze(["badgeAutista", "badge"]),
        }),
        mezzo: Object.freeze({
          targa: Object.freeze(["mezzoTarga", "targaMotrice", "targaRimorchio", "targa"]),
        }),
        sessioneAttiva: Object.freeze({
          badge: Object.freeze(["badgeAutista"]),
          targaMotrice: Object.freeze(["targaMotrice"]),
          targaRimorchio: Object.freeze(["targaRimorchio"]),
          timestamp: Object.freeze(["timestamp"]),
        }),
      }),
      requestLimits: Object.freeze({
        maxDocumentReadsPerRequest: 1,
        maxReturnedVehicleRecords: 20,
      }),
    }),
    // Boundary: internal-ai-firebase-readonly-boundary.js:667-684.
    "vehicles.mezziAziendali": Object.freeze({
      key: "vehicles.mezziAziendali",
      boundaryEntryId: "firestore-storage-mezzi-aziendali-doc",
      datasetKey: "@mezzi_aziendali",
      accessMode: "exact_document",
      collection: "storage",
      docId: "@mezzi_aziendali",
      sourceOfTruth:
        "registry v0.6 BOZZA + boundary firestore-storage-mezzi-aziendali-doc (post C-FIX 2026-05-04)",
      matchStrategy: "single_targa_exact_match",
      viewBindings: Object.freeze(["Driver360", "Vehicle360"]),
      allowedFields: Object.freeze([
        "id",
        "targa",
        "categoria",
        "marca",
        "modello",
        "autistaId",
        "autistaNome",
        "librettoStoragePath",
        "dataImmatricolazione",
        "dataScadenzaRevisione",
        "dataUltimoCollaudo",
        "fotoPath",
        "telaio",
        "massaComplessiva",
      ]),
      forbiddenFields: Object.freeze([]),
      aliases: Object.freeze({
        mezzo: Object.freeze({
          id: Object.freeze(["id"]),
          targa: Object.freeze(["targa"]),
          categoria: Object.freeze(["categoria"]),
          marca: Object.freeze(["marca"]),
          modello: Object.freeze(["modello"]),
          telaio: Object.freeze(["telaio"]),
        }),
        autista: Object.freeze({
          id: Object.freeze(["autistaId"]),
          displayName: Object.freeze(["autistaNome"]),
        }),
        documento: Object.freeze({
          librettoPath: Object.freeze(["librettoStoragePath"]),
          fotoPath: Object.freeze(["fotoPath"]),
        }),
      }),
      requestLimits: Object.freeze({
        maxDocumentReadsPerRequest: 1,
        maxReturnedVehicleRecords: 1,
      }),
    }),
    // Boundary: internal-ai-firebase-readonly-boundary.js:787-814.
    "refuelings.rifornimentiAutistiTmp": Object.freeze({
      key: "refuelings.rifornimentiAutistiTmp",
      boundaryEntryId: "firestore-storage-rifornimenti-autisti-tmp-doc",
      datasetKey: "@rifornimenti_autisti_tmp",
      accessMode: "exact_document",
      collection: "storage",
      docId: "@rifornimenti_autisti_tmp",
      sourceOfTruth: "registry v0.6 BOZZA + boundary firestore-storage-rifornimenti-autisti-tmp-doc",
      matchStrategy: "driver_id_and_plate_exact_match",
      viewBindings: Object.freeze(["Driver360", "Vehicle360"]),
      allowedFields: Object.freeze([
        "id",
        "originId",
        "autistaId",
        "badgeAutista",
        "badge",
        "mezzoTarga",
        "targa",
        "targaMotrice",
        "timestamp",
        "data",
        "litri",
        "km",
        "confermatoAutista",
      ]),
      forbiddenFields: Object.freeze([
        "note",
        "descrizione",
        "messaggio",
        "distributore",
        "fornitore",
        "importo",
        "costo",
      ]),
      aliases: Object.freeze({
        rifornimento: Object.freeze({
          id: Object.freeze(["id", "originId"]),
          data: Object.freeze(["data", "timestamp"]),
          quantita: Object.freeze(["litri"]),
          km: Object.freeze(["km"]),
        }),
        autista: Object.freeze({
          id: Object.freeze(["autistaId"]),
          badge: Object.freeze(["badgeAutista", "badge"]),
        }),
        mezzo: Object.freeze({
          targa: Object.freeze(["mezzoTarga", "targa", "targaMotrice"]),
        }),
      }),
      requestLimits: Object.freeze({
        maxDocumentReadsPerRequest: 1,
        maxReturnedVehicleRecords: 20,
      }),
    }),
    // Boundary: internal-ai-firebase-readonly-boundary.js:1230-1246.
    "refuelings.rifornimenti": Object.freeze({
      key: "refuelings.rifornimenti",
      boundaryEntryId: "firestore-storage-rifornimenti-doc",
      datasetKey: "@rifornimenti",
      accessMode: "exact_document",
      collection: "storage",
      docId: "@rifornimenti",
      sourceOfTruth: "registry v0.6 BOZZA + boundary firestore-storage-rifornimenti-doc",
      matchStrategy: "vehicle_plate_exact_match",
      viewBindings: Object.freeze(["Vehicle360", "Ricerca360"]),
      allowedFields: Object.freeze([
        "id",
        "targa",
        "mezzoTarga",
        "targaMotrice",
        "autistaId",
        "badgeAutista",
        "data",
        "timestamp",
        "litri",
        "km",
        "costo",
        "distributore",
        "sourceRecordId",
      ]),
      forbiddenFields: Object.freeze([
        "note",
        "descrizione",
        "messaggio",
        "commento",
        "testo",
        "dettaglio",
        "rawText",
        "extractedText",
        "riepilogoBreve",
        "analisiCosti",
        "anomalie",
        "fornitoriNotevoli",
        "apiKey",
        "token",
        "password",
        "secret",
        "telefono",
        "telefonoPrivato",
        "telefoniAggiuntivi",
        "email",
        "indirizzo",
        "pinSim",
        "pukSim",
        "schedeCarburante",
        "downloadUrl",
        "fileUrl",
        "pdfUrl",
        "url",
        "imageUrls",
        "fotoUrl",
        "fornitore",
        "importo",
      ]),
      aliases: Object.freeze({
        rifornimento: Object.freeze({
          id: Object.freeze(["id", "sourceRecordId"]),
          data: Object.freeze(["data", "timestamp"]),
          quantita: Object.freeze(["litri"]),
          km: Object.freeze(["km"]),
          costo: Object.freeze(["costo"]),
          distributore: Object.freeze(["distributore"]),
        }),
        autista: Object.freeze({
          id: Object.freeze(["autistaId"]),
          badge: Object.freeze(["badgeAutista"]),
        }),
        mezzo: Object.freeze({
          targa: Object.freeze(["targa", "mezzoTarga", "targaMotrice"]),
        }),
      }),
      requestLimits: Object.freeze({
        maxDocumentReadsPerRequest: 1,
        maxReturnedVehicleRecords: 100,
      }),
    }),
    // Boundary: internal-ai-firebase-readonly-boundary.js:1083-1096.
    "maintenance.manutenzioni": Object.freeze({
      key: "maintenance.manutenzioni",
      boundaryEntryId: "firestore-storage-manutenzioni-doc",
      datasetKey: "@manutenzioni",
      accessMode: "exact_document",
      collection: "storage",
      docId: "@manutenzioni",
      sourceOfTruth: "registry v0.6 BOZZA + boundary firestore-storage-manutenzioni-doc",
      matchStrategy: "vehicle_plate_exact_match",
      viewBindings: Object.freeze(["Vehicle360", "Ricerca360"]),
      allowedFields: Object.freeze([
        "id",
        "targa",
        "mezzoTarga",
        "data",
        "timestamp",
        "tipo",
        "stato",
        "lavorazioni",
        "materiali",
        "km",
        "sourceDocumentId",
        "sourceRecordId",
        "officinaId",
        "officina",
        "eseguito",
        "fornitore",
        "importo",
        "ore",
        "sottotipo",
      ]),
      forbiddenFields: Object.freeze([
        "note",
        "descrizione",
        "messaggio",
        "commento",
        "testo",
        "dettaglio",
        "rawText",
        "extractedText",
        "riepilogoBreve",
        "analisiCosti",
        "anomalie",
        "fornitoriNotevoli",
      ]),
      aliases: Object.freeze({
        manutenzione: Object.freeze({
          id: Object.freeze(["id", "sourceRecordId"]),
          data: Object.freeze(["data", "timestamp"]),
          tipo: Object.freeze(["tipo", "sottotipo"]),
          stato: Object.freeze(["stato", "eseguito"]),
          km: Object.freeze(["km", "ore"]),
        }),
        mezzo: Object.freeze({
          targa: Object.freeze(["targa", "mezzoTarga"]),
        }),
        fornitore: Object.freeze({
          id: Object.freeze(["officinaId"]),
          nome: Object.freeze(["officina", "fornitore"]),
        }),
      }),
      requestLimits: Object.freeze({
        maxDocumentReadsPerRequest: 1,
        maxReturnedVehicleRecords: 100,
      }),
    }),
    // Boundary: internal-ai-firebase-readonly-boundary.js:1050-1063.
    "work.lavori": Object.freeze({
      key: "work.lavori",
      boundaryEntryId: "firestore-storage-lavori-doc",
      datasetKey: "@lavori",
      accessMode: "exact_document",
      collection: "storage",
      docId: "@lavori",
      sourceOfTruth: "registry v0.6 BOZZA + boundary firestore-storage-lavori-doc",
      matchStrategy: "vehicle_or_site_exact_match",
      viewBindings: Object.freeze(["Vehicle360", "Site360", "Ricerca360"]),
      allowedFields: Object.freeze([
        "id",
        "targa",
        "mezzoTarga",
        "cantiere",
        "cantiereId",
        "stato",
        "data",
        "timestamp",
        "dataInizio",
        "dataFine",
        "tipo",
        "lavorazione",
        "dataEsecuzione",
        "dataInserimento",
        "eseguito",
        "gruppoId",
        "sourceRecordId",
        "sottoElementi",
        "source",
        "urgenza",
      ]),
      forbiddenFields: Object.freeze([
        "note",
        "descrizione",
        "messaggio",
        "commento",
        "testo",
        "dettaglio",
        "rawText",
        "extractedText",
        "riepilogoBreve",
        "analisiCosti",
        "anomalie",
        "fornitoriNotevoli",
      ]),
      aliases: Object.freeze({
        lavoro: Object.freeze({
          id: Object.freeze(["id", "gruppoId", "sourceRecordId"]),
          data: Object.freeze(["data", "timestamp", "dataInizio", "dataEsecuzione", "dataInserimento"]),
          stato: Object.freeze(["stato", "eseguito"]),
          tipo: Object.freeze(["tipo", "lavorazione"]),
        }),
        mezzo: Object.freeze({
          targa: Object.freeze(["targa", "mezzoTarga"]),
        }),
        cantiere: Object.freeze({
          id: Object.freeze(["cantiereId"]),
          label: Object.freeze(["cantiere"]),
        }),
      }),
      requestLimits: Object.freeze({
        maxDocumentReadsPerRequest: 1,
        maxReturnedVehicleRecords: 100,
      }),
    }),
    // Boundary: internal-ai-firebase-readonly-boundary.js:1035-1048.
    "inventory.inventario": Object.freeze({
      key: "inventory.inventario",
      boundaryEntryId: "firestore-storage-inventario-doc",
      datasetKey: "@inventario",
      accessMode: "exact_document",
      collection: "storage",
      docId: "@inventario",
      sourceOfTruth: "registry v0.6 BOZZA + boundary firestore-storage-inventario-doc",
      matchStrategy: "material_code_and_name_exact_match",
      viewBindings: Object.freeze(["Site360", "Ricerca360"]),
      allowedFields: Object.freeze([
        "id",
        "codice",
        "nome",
        "articolo",
        "materiale",
        "categoria",
        "quantita",
        "unita",
        "ubicazione",
        "stockKey",
        "fornitore",
        "fornitoreLabel",
        "nomeFornitore",
        "prezzoUnitario",
        "quantitaTotale",
        "stockLoadKeys",
        "fotoStoragePath",
        "updatedAt",
      ]),
      forbiddenFields: Object.freeze([
        "note",
        "descrizione",
        "messaggio",
        "commento",
        "testo",
        "dettaglio",
        "rawText",
        "extractedText",
        "riepilogoBreve",
        "analisiCosti",
        "anomalie",
        "fornitoriNotevoli",
      ]),
      aliases: Object.freeze({
        materiale: Object.freeze({
          id: Object.freeze(["id", "stockKey"]),
          codice: Object.freeze(["codice"]),
          nome: Object.freeze(["nome", "articolo", "materiale"]),
          quantita: Object.freeze(["quantita", "quantitaTotale"]),
        }),
        fornitore: Object.freeze({
          nome: Object.freeze(["fornitore", "fornitoreLabel", "nomeFornitore"]),
        }),
      }),
      requestLimits: Object.freeze({
        maxDocumentReadsPerRequest: 1,
        maxReturnedVehicleRecords: 100,
      }),
    }),
    // Boundary: internal-ai-firebase-readonly-boundary.js:1098-1111.
    "materials.materialiConsegnati": Object.freeze({
      key: "materials.materialiConsegnati",
      boundaryEntryId: "firestore-storage-materiali-consegnati-doc",
      datasetKey: "@materialiconsegnati",
      accessMode: "exact_document",
      collection: "storage",
      docId: "@materialiconsegnati",
      sourceOfTruth: "registry v0.6 BOZZA + boundary firestore-storage-materiali-consegnati-doc",
      matchStrategy: "material_or_vehicle_exact_match",
      viewBindings: Object.freeze(["Vehicle360", "Site360", "Ricerca360"]),
      allowedFields: Object.freeze([
        "id",
        "materiale",
        "codice",
        "nome",
        "quantita",
        "unita",
        "targa",
        "mezzoTarga",
        "lavoroId",
        "destinatario",
        "timestamp",
        "data",
        "cantiere",
        "cantiereId",
        "sourceRecordId",
        "direzione",
        "fornitore",
        "fornitoreLabel",
        "inventarioRefId",
        "materialeLabel",
        "motivo",
        "origine",
        "stockKey",
        "target",
        "tipo",
      ]),
      forbiddenFields: Object.freeze([
        "note",
        "descrizione",
        "messaggio",
        "commento",
        "testo",
        "dettaglio",
        "rawText",
        "extractedText",
        "riepilogoBreve",
        "analisiCosti",
        "anomalie",
        "fornitoriNotevoli",
      ]),
      aliases: Object.freeze({
        materiale: Object.freeze({
          id: Object.freeze(["id", "inventarioRefId", "stockKey", "sourceRecordId"]),
          codice: Object.freeze(["codice"]),
          nome: Object.freeze(["nome", "materiale", "materialeLabel"]),
          quantita: Object.freeze(["quantita"]),
        }),
        mezzo: Object.freeze({
          targa: Object.freeze(["targa", "mezzoTarga"]),
        }),
        cantiere: Object.freeze({
          id: Object.freeze(["cantiereId"]),
          label: Object.freeze(["cantiere"]),
        }),
      }),
      requestLimits: Object.freeze({
        maxDocumentReadsPerRequest: 1,
        maxReturnedVehicleRecords: 100,
      }),
    }),
    // Boundary: internal-ai-firebase-readonly-boundary.js:1158-1174.
    "orders.ordini": Object.freeze({
      key: "orders.ordini",
      boundaryEntryId: "firestore-storage-ordini-doc",
      datasetKey: "@ordini",
      accessMode: "exact_document",
      collection: "storage",
      docId: "@ordini",
      sourceOfTruth: "registry v0.6 BOZZA + boundary firestore-storage-ordini-doc",
      matchStrategy: "material_or_supplier_exact_match",
      viewBindings: Object.freeze(["Site360", "Ricerca360"]),
      allowedFields: Object.freeze([
        "id",
        "supplierId",
        "idFornitore",
        "fornitoreId",
        "fornitore",
        "nomeFornitore",
        "supplierName",
        "orderDate",
        "data",
        "dataOrdine",
        "timestamp",
        "stato",
        "state",
        "materiali",
        "righe",
        "items",
        "voci",
        "orderReference",
        "numeroOrdine",
        "totalRows",
        "arrivedRows",
        "pendingRows",
        "arrivato",
        "updatedAt",
      ]),
      forbiddenFields: Object.freeze([
        "note",
        "descrizione",
        "messaggio",
        "commento",
        "testo",
        "dettaglio",
        "rawText",
        "extractedText",
        "riepilogoBreve",
        "analisiCosti",
        "anomalie",
        "fornitoriNotevoli",
        "apiKey",
        "token",
        "password",
        "secret",
        "telefono",
        "telefonoPrivato",
        "telefoniAggiuntivi",
        "email",
        "indirizzo",
        "pinSim",
        "pukSim",
        "schedeCarburante",
        "downloadUrl",
        "fileUrl",
        "pdfUrl",
        "url",
        "imageUrls",
        "fotoUrl",
      ]),
      aliases: Object.freeze({
        ordine: Object.freeze({
          id: Object.freeze(["id", "orderReference", "numeroOrdine"]),
          data: Object.freeze(["orderDate", "data", "dataOrdine", "timestamp"]),
          stato: Object.freeze(["stato", "state", "arrivato"]),
          righe: Object.freeze(["materiali", "righe", "items", "voci"]),
        }),
        fornitore: Object.freeze({
          id: Object.freeze(["supplierId", "idFornitore", "fornitoreId"]),
          nome: Object.freeze(["fornitore", "nomeFornitore", "supplierName"]),
        }),
      }),
      requestLimits: Object.freeze({
        maxDocumentReadsPerRequest: 1,
        maxReturnedVehicleRecords: 100,
      }),
    }),
    // Boundary: internal-ai-firebase-readonly-boundary.js:1176-1192.
    "quotes.preventivi": Object.freeze({
      key: "quotes.preventivi",
      boundaryEntryId: "firestore-storage-preventivi-doc",
      datasetKey: "@preventivi",
      accessMode: "exact_document",
      collection: "storage",
      docId: "@preventivi",
      sourceOfTruth: "registry v0.6 BOZZA + boundary firestore-storage-preventivi-doc",
      matchStrategy: "supplier_or_material_exact_match",
      viewBindings: Object.freeze(["Vehicle360", "Site360", "Ricerca360"]),
      allowedFields: Object.freeze([
        "id",
        "supplierId",
        "fornitoreId",
        "fornitore",
        "nomeFornitore",
        "supplierName",
        "numeroPreventivo",
        "dataPreventivo",
        "data",
        "timestamp",
        "ambitoPreventivo",
        "famigliaArchivista",
        "righe",
        "voci",
        "rows",
        "totalAmount",
        "totale",
        "valuta",
        "currency",
        "approvalStatus",
        "ricevutoDaWhatsapp",
        "ricevutoDaEmail",
        "pdfStoragePath",
        "imageStoragePaths",
        "storagePath",
        "createdAt",
        "fornitoreNome",
        "updatedAt",
      ]),
      forbiddenFields: Object.freeze([
        "note",
        "descrizione",
        "messaggio",
        "commento",
        "testo",
        "dettaglio",
        "rawText",
        "extractedText",
        "riepilogoBreve",
        "analisiCosti",
        "anomalie",
        "fornitoriNotevoli",
        "apiKey",
        "token",
        "password",
        "secret",
        "telefono",
        "telefonoPrivato",
        "telefoniAggiuntivi",
        "email",
        "indirizzo",
        "pinSim",
        "pukSim",
        "schedeCarburante",
        "downloadUrl",
        "fileUrl",
        "pdfUrl",
        "url",
        "imageUrls",
        "fotoUrl",
      ]),
      aliases: Object.freeze({
        preventivo: Object.freeze({
          id: Object.freeze(["id", "numeroPreventivo"]),
          data: Object.freeze(["dataPreventivo", "data", "timestamp", "createdAt", "updatedAt"]),
          righe: Object.freeze(["righe", "voci", "rows"]),
          totale: Object.freeze(["totalAmount", "totale"]),
          stato: Object.freeze(["approvalStatus"]),
        }),
        fornitore: Object.freeze({
          id: Object.freeze(["supplierId", "fornitoreId"]),
          nome: Object.freeze(["fornitore", "nomeFornitore", "supplierName", "fornitoreNome"]),
        }),
      }),
      requestLimits: Object.freeze({
        maxDocumentReadsPerRequest: 1,
        maxReturnedVehicleRecords: 100,
      }),
    }),
    // Boundary: internal-ai-firebase-readonly-boundary.js:1194-1207.
    "quotes.preventiviApprovazioni": Object.freeze({
      key: "quotes.preventiviApprovazioni",
      boundaryEntryId: "firestore-storage-preventivi-approvazioni-doc",
      datasetKey: "@preventivi_approvazioni",
      accessMode: "exact_document",
      collection: "storage",
      docId: "@preventivi_approvazioni",
      sourceOfTruth: "registry v0.6 BOZZA + boundary firestore-storage-preventivi-approvazioni-doc",
      matchStrategy: "preventivo_or_plate_exact_match",
      viewBindings: Object.freeze(["Vehicle360", "Ricerca360"]),
      allowedFields: Object.freeze([
        "id",
        "approvalKey",
        "targa",
        "sourceKey",
        "sourceDocId",
        "status",
        "updatedAt",
        "timestamp",
        "preventivoId",
      ]),
      forbiddenFields: Object.freeze([
        "note",
        "descrizione",
        "messaggio",
        "commento",
        "testo",
        "dettaglio",
        "rawText",
        "extractedText",
        "riepilogoBreve",
        "analisiCosti",
        "anomalie",
        "fornitoriNotevoli",
      ]),
      aliases: Object.freeze({
        approvazione: Object.freeze({
          id: Object.freeze(["id", "approvalKey", "preventivoId", "sourceDocId"]),
          stato: Object.freeze(["status"]),
          data: Object.freeze(["updatedAt", "timestamp"]),
        }),
        mezzo: Object.freeze({
          targa: Object.freeze(["targa"]),
        }),
      }),
      requestLimits: Object.freeze({
        maxDocumentReadsPerRequest: 1,
        maxReturnedVehicleRecords: 100,
      }),
    }),
    // Boundary: internal-ai-firebase-readonly-boundary.js:984-1000.
    "suppliers.fornitori": Object.freeze({
      key: "suppliers.fornitori",
      boundaryEntryId: "firestore-storage-fornitori-doc",
      datasetKey: "@fornitori",
      accessMode: "exact_document",
      collection: "storage",
      docId: "@fornitori",
      sourceOfTruth: "registry v0.6 BOZZA + boundary firestore-storage-fornitori-doc",
      matchStrategy: "supplier_name_exact_match",
      viewBindings: Object.freeze(["Site360", "Ricerca360"]),
      allowedFields: Object.freeze([
        "id",
        "nome",
        "ragioneSociale",
        "fornitore",
        "label",
        "badge",
        "codice",
      ]),
      forbiddenFields: Object.freeze([
        "note",
        "descrizione",
        "messaggio",
        "commento",
        "testo",
        "dettaglio",
        "rawText",
        "extractedText",
        "riepilogoBreve",
        "analisiCosti",
        "anomalie",
        "fornitoriNotevoli",
        "apiKey",
        "token",
        "password",
        "secret",
        "telefono",
        "telefonoPrivato",
        "telefoniAggiuntivi",
        "email",
        "indirizzo",
        "pinSim",
        "pukSim",
        "schedeCarburante",
        "downloadUrl",
        "fileUrl",
        "pdfUrl",
        "url",
        "imageUrls",
        "fotoUrl",
      ]),
      aliases: Object.freeze({
        fornitore: Object.freeze({
          id: Object.freeze(["id", "badge", "codice"]),
          nome: Object.freeze(["nome", "ragioneSociale", "fornitore", "label"]),
        }),
      }),
      requestLimits: Object.freeze({
        maxDocumentReadsPerRequest: 1,
        maxReturnedVehicleRecords: 50,
      }),
    }),
    // Boundary: internal-ai-firebase-readonly-boundary.js:1143-1156.
    "workshops.officine": Object.freeze({
      key: "workshops.officine",
      boundaryEntryId: "firestore-storage-officine-doc",
      datasetKey: "@officine",
      accessMode: "exact_document",
      collection: "storage",
      docId: "@officine",
      sourceOfTruth: "registry v0.6 BOZZA + boundary firestore-storage-officine-doc",
      matchStrategy: "workshop_name_exact_match",
      viewBindings: Object.freeze(["Vehicle360", "Ricerca360"]),
      allowedFields: Object.freeze([
        "id",
        "nome",
        "ragioneSociale",
        "officina",
        "label",
        "citta",
      ]),
      forbiddenFields: Object.freeze([
        "apiKey",
        "token",
        "password",
        "secret",
        "telefono",
        "telefonoPrivato",
        "telefoniAggiuntivi",
        "email",
        "indirizzo",
        "pinSim",
        "pukSim",
        "schedeCarburante",
        "downloadUrl",
        "fileUrl",
        "pdfUrl",
        "url",
        "imageUrls",
        "fotoUrl",
      ]),
      aliases: Object.freeze({
        officina: Object.freeze({
          id: Object.freeze(["id"]),
          nome: Object.freeze(["nome", "ragioneSociale", "officina", "label"]),
          citta: Object.freeze(["citta"]),
        }),
      }),
      requestLimits: Object.freeze({
        maxDocumentReadsPerRequest: 1,
        maxReturnedVehicleRecords: 50,
      }),
    }),
    "documents.documentiMezziRoot": Object.freeze({
      key: "documents.documentiMezziRoot",
      boundaryEntryId: "firestore-documenti-mezzi-root",
      datasetKey: "@documenti_mezzi",
      accessMode: "collection_root",
      collection: "@documenti_mezzi",
      sourceOfTruth: "registry v0.6 BOZZA + writer reali documenti mezzi root",
      matchStrategy: "vehicle_plate_exact_match",
      viewBindings: Object.freeze(["Vehicle360", "Ricerca360"]),
      allowedFields: Object.freeze([
        "id",
        "__docId",
        "tipoDocumento",
        "categoriaArchivio",
        "sottotipoDocumentoMezzo",
        "fornitore",
        "numeroDocumento",
        "dataDocumento",
        "targa",
        "marca",
        "modello",
        "telaio",
        "km",
        "riferimentoPreventivoNumero",
        "riferimentoPreventivoData",
        "imponibile",
        "ivaPercentuale",
        "ivaImporto",
        "totaleDocumento",
        "valuta",
        "currency",
        "valutaDocumento",
        "voci",
        "importoPagamento",
        "nomeFile",
        "fileStoragePath",
        "fonte",
        "famigliaArchivista",
        "statoArchivio",
        "createdAt",
        "daVerificare",
        "targaEstrattaIA",
        "mezzoId",
        "proprietario",
        "assicurazione",
        "dataImmatricolazione",
        "dataScadenza",
        "dataUltimoCollaudo",
        "dataScadenzaRevisione",
        "documentoMezzoAggiornamentoConfermato",
        "duplicateChoice",
        "duplicateOfId",
        "duplicateTarget",
        "archivedAsDifferentFromId",
      ]),
      forbiddenFields: Object.freeze([
        "note",
        "descrizione",
        "messaggio",
        "commento",
        "testo",
        "dettaglio",
        "rawText",
        "extractedText",
        "riepilogoBreve",
        "analisiCosti",
        "anomalie",
        "fornitoriNotevoli",
        "apiKey",
        "token",
        "password",
        "secret",
        "telefono",
        "telefonoPrivato",
        "telefoniAggiuntivi",
        "email",
        "indirizzo",
        "pinSim",
        "pukSim",
        "schedeCarburante",
        "downloadUrl",
        "fileUrl",
        "pdfUrl",
        "url",
        "imageUrls",
        "fotoUrl",
      ]),
      aliases: Object.freeze({
        documento: Object.freeze({
          id: Object.freeze(["id", "__docId", "numeroDocumento"]),
          data: Object.freeze(["dataDocumento", "createdAt"]),
          totale: Object.freeze(["totaleDocumento", "imponibile", "importoPagamento"]),
          tipo: Object.freeze(["tipoDocumento", "sottotipoDocumentoMezzo", "categoriaArchivio"]),
        }),
        mezzo: Object.freeze({
          targa: Object.freeze(["targa"]),
          telaio: Object.freeze(["telaio"]),
          id: Object.freeze(["mezzoId"]),
        }),
        fornitore: Object.freeze({
          nome: Object.freeze(["fornitore"]),
        }),
      }),
      requestLimits: Object.freeze({
        maxDocumentReadsPerRequest: 50,
        maxReturnedVehicleRecords: 50,
      }),
    }),
    "documents.documentiMagazzinoRoot": Object.freeze({
      key: "documents.documentiMagazzinoRoot",
      boundaryEntryId: "firestore-documenti-magazzino-root",
      datasetKey: "@documenti_magazzino",
      accessMode: "collection_root",
      collection: "@documenti_magazzino",
      sourceOfTruth: "registry v0.6 BOZZA + writer reali documenti magazzino root",
      matchStrategy: "document_material_or_supplier_exact_match",
      viewBindings: Object.freeze(["Site360", "Ricerca360"]),
      allowedFields: Object.freeze([
        "id",
        "__docId",
        "tipoDocumento",
        "categoriaArchivio",
        "fornitore",
        "numeroDocumento",
        "dataDocumento",
        "targa",
        "imponibile",
        "ivaPercentuale",
        "ivaImporto",
        "totaleDocumento",
        "valuta",
        "currency",
        "valutaDocumento",
        "voci",
        "importoPagamento",
        "nomeFile",
        "fileStoragePath",
        "fonte",
        "famigliaArchivista",
        "statoArchivio",
        "createdAt",
        "daVerificare",
        "targaEstrattaIA",
        "duplicateChoice",
        "duplicateOfId",
        "duplicateTarget",
        "archivedAsDifferentFromId",
      ]),
      forbiddenFields: Object.freeze([
        "note",
        "descrizione",
        "messaggio",
        "commento",
        "testo",
        "dettaglio",
        "rawText",
        "extractedText",
        "riepilogoBreve",
        "analisiCosti",
        "anomalie",
        "fornitoriNotevoli",
        "apiKey",
        "token",
        "password",
        "secret",
        "telefono",
        "telefonoPrivato",
        "telefoniAggiuntivi",
        "email",
        "indirizzo",
        "pinSim",
        "pukSim",
        "schedeCarburante",
        "downloadUrl",
        "fileUrl",
        "pdfUrl",
        "url",
        "imageUrls",
        "fotoUrl",
      ]),
      aliases: Object.freeze({
        documento: Object.freeze({
          id: Object.freeze(["id", "__docId", "numeroDocumento"]),
          data: Object.freeze(["dataDocumento", "createdAt"]),
          totale: Object.freeze(["totaleDocumento", "imponibile", "importoPagamento"]),
          righe: Object.freeze(["voci"]),
        }),
        fornitore: Object.freeze({
          nome: Object.freeze(["fornitore"]),
        }),
      }),
      requestLimits: Object.freeze({
        maxDocumentReadsPerRequest: 50,
        maxReturnedVehicleRecords: 50,
      }),
    }),
    "documents.documentiGenericiRoot": Object.freeze({
      key: "documents.documentiGenericiRoot",
      boundaryEntryId: "firestore-documenti-generici-root",
      datasetKey: "@documenti_generici",
      accessMode: "collection_root",
      collection: "@documenti_generici",
      sourceOfTruth: "registry v0.6 BOZZA + writer reale documenti generici root",
      matchStrategy: "document_metadata_exact_match",
      viewBindings: Object.freeze(["Site360", "Ricerca360"]),
      allowedFields: Object.freeze([
        "id",
        "__docId",
        "tipoDocumento",
        "categoriaArchivio",
        "fornitore",
        "numeroDocumento",
        "dataDocumento",
        "targa",
        "marca",
        "modello",
        "telaio",
        "km",
        "riferimentoPreventivoNumero",
        "riferimentoPreventivoData",
        "imponibile",
        "ivaPercentuale",
        "ivaImporto",
        "totaleDocumento",
        "valuta",
        "currency",
        "voci",
        "importoPagamento",
        "nomeFile",
        "createdAt",
        "fonte",
        "daVerificare",
        "targaEstrattaIA",
      ]),
      forbiddenFields: Object.freeze([
        "note",
        "descrizione",
        "messaggio",
        "commento",
        "testo",
        "dettaglio",
        "rawText",
        "extractedText",
        "riepilogoBreve",
        "analisiCosti",
        "anomalie",
        "fornitoriNotevoli",
        "apiKey",
        "token",
        "password",
        "secret",
        "telefono",
        "telefonoPrivato",
        "telefoniAggiuntivi",
        "email",
        "indirizzo",
        "pinSim",
        "pukSim",
        "schedeCarburante",
        "downloadUrl",
        "fileUrl",
        "pdfUrl",
        "url",
        "imageUrls",
        "fotoUrl",
      ]),
      aliases: Object.freeze({
        documento: Object.freeze({
          id: Object.freeze(["id", "__docId", "numeroDocumento"]),
          data: Object.freeze(["dataDocumento", "createdAt"]),
          totale: Object.freeze(["totaleDocumento", "imponibile", "importoPagamento"]),
          tipo: Object.freeze(["tipoDocumento", "categoriaArchivio"]),
        }),
        fornitore: Object.freeze({
          nome: Object.freeze(["fornitore"]),
        }),
      }),
      requestLimits: Object.freeze({
        maxDocumentReadsPerRequest: 50,
        maxReturnedVehicleRecords: 50,
      }),
    }),
    "cisterna.documentiRoot": Object.freeze({
      key: "cisterna.documentiRoot",
      boundaryEntryId: "firestore-documenti-cisterna-root",
      datasetKey: "@documenti_cisterna",
      accessMode: "collection_root",
      collection: "@documenti_cisterna",
      sourceOfTruth: "registry v0.6 BOZZA + writer reale NEXT Cisterna IA",
      matchStrategy: "cisterna_period_or_supplier_exact_match",
      viewBindings: Object.freeze(["Site360", "Ricerca360"]),
      allowedFields: Object.freeze([
        "id",
        "__docId",
        "tipoDocumento",
        "fornitore",
        "destinatario",
        "numeroDocumento",
        "dataDocumento",
        "yearMonth",
        "mese",
        "litriTotali",
        "litri15C",
        "totaleDocumento",
        "valuta",
        "currency",
        "prodotto",
        "daVerificare",
        "storagePath",
        "nomeFile",
        "fonte",
        "createdAt",
        "updatedAt",
        "iaEngine",
        "dupGroupKey",
        "dupChosen",
        "dupIgnored",
      ]),
      forbiddenFields: Object.freeze([
        "note",
        "descrizione",
        "messaggio",
        "commento",
        "testo",
        "dettaglio",
        "rawText",
        "extractedText",
        "riepilogoBreve",
        "analisiCosti",
        "anomalie",
        "fornitoriNotevoli",
        "apiKey",
        "token",
        "password",
        "secret",
        "telefono",
        "telefonoPrivato",
        "telefoniAggiuntivi",
        "email",
        "indirizzo",
        "pinSim",
        "pukSim",
        "schedeCarburante",
        "downloadUrl",
        "fileUrl",
        "pdfUrl",
        "url",
        "imageUrls",
        "fotoUrl",
      ]),
      aliases: Object.freeze({
        documento: Object.freeze({
          id: Object.freeze(["id", "__docId", "numeroDocumento"]),
          data: Object.freeze(["dataDocumento", "createdAt", "updatedAt"]),
          totale: Object.freeze(["totaleDocumento"]),
          periodo: Object.freeze(["yearMonth", "mese"]),
        }),
        cisterna: Object.freeze({
          litri: Object.freeze(["litriTotali", "litri15C"]),
          prodotto: Object.freeze(["prodotto"]),
        }),
        fornitore: Object.freeze({
          nome: Object.freeze(["fornitore"]),
        }),
      }),
      requestLimits: Object.freeze({
        maxDocumentReadsPerRequest: 50,
        maxReturnedVehicleRecords: 50,
      }),
    }),
    "cisterna.schedeIaRoot": Object.freeze({
      key: "cisterna.schedeIaRoot",
      boundaryEntryId: "firestore-cisterna-schede-ia-root",
      datasetKey: "@cisterna_schede_ia",
      accessMode: "collection_root",
      collection: "@cisterna_schede_ia",
      sourceOfTruth: "registry v0.6 BOZZA + writer reale NEXT Cisterna schede",
      matchStrategy: "cisterna_scheda_month_exact_match",
      viewBindings: Object.freeze(["Site360", "Ricerca360"]),
      allowedFields: Object.freeze([
        "id",
        "__docId",
        "source",
        "fonte",
        "rowCount",
        "rows",
        "needsReview",
        "yearMonth",
        "storagePath",
        "nomeFile",
        "iaEngine",
        "createdAt",
        "updatedAt",
      ]),
      forbiddenFields: Object.freeze([
        "note",
        "descrizione",
        "messaggio",
        "commento",
        "testo",
        "dettaglio",
        "rawText",
        "extractedText",
        "riepilogoBreve",
        "analisiCosti",
        "anomalie",
        "fornitoriNotevoli",
        "apiKey",
        "token",
        "password",
        "secret",
        "telefono",
        "telefonoPrivato",
        "telefoniAggiuntivi",
        "email",
        "indirizzo",
        "pinSim",
        "pukSim",
        "schedeCarburante",
        "downloadUrl",
        "fileUrl",
        "pdfUrl",
        "url",
        "imageUrls",
        "fotoUrl",
      ]),
      aliases: Object.freeze({
        scheda: Object.freeze({
          id: Object.freeze(["id", "__docId"]),
          periodo: Object.freeze(["yearMonth"]),
          righe: Object.freeze(["rows"]),
          conteggio: Object.freeze(["rowCount"]),
        }),
      }),
      requestLimits: Object.freeze({
        maxDocumentReadsPerRequest: 50,
        maxReturnedVehicleRecords: 50,
      }),
    }),
    "cisterna.parametriMensiliRoot": Object.freeze({
      key: "cisterna.parametriMensiliRoot",
      boundaryEntryId: "firestore-cisterna-parametri-mensili-root",
      datasetKey: "@cisterna_parametri_mensili",
      accessMode: "collection_root",
      collection: "@cisterna_parametri_mensili",
      sourceOfTruth: "registry v0.6 BOZZA + writer reale NEXT Cisterna parametri mensili",
      matchStrategy: "cisterna_month_exact_match",
      viewBindings: Object.freeze(["Site360", "Ricerca360"]),
      allowedFields: Object.freeze([
        "id",
        "__docId",
        "mese",
        "cambioEurChf",
        "updatedAt",
      ]),
      forbiddenFields: Object.freeze([
        "note",
        "descrizione",
        "messaggio",
        "commento",
        "testo",
        "dettaglio",
        "rawText",
        "extractedText",
        "riepilogoBreve",
        "analisiCosti",
        "anomalie",
        "fornitoriNotevoli",
        "apiKey",
        "token",
        "password",
        "secret",
        "telefono",
        "telefonoPrivato",
        "telefoniAggiuntivi",
        "email",
        "indirizzo",
        "pinSim",
        "pukSim",
        "schedeCarburante",
        "downloadUrl",
        "fileUrl",
        "pdfUrl",
        "url",
        "imageUrls",
        "fotoUrl",
      ]),
      aliases: Object.freeze({
        parametro: Object.freeze({
          id: Object.freeze(["id", "__docId", "mese"]),
          periodo: Object.freeze(["mese"]),
          cambio: Object.freeze(["cambioEurChf"]),
        }),
      }),
      requestLimits: Object.freeze({
        maxDocumentReadsPerRequest: 50,
        maxReturnedVehicleRecords: 50,
      }),
    }),
    // Boundary: internal-ai-firebase-readonly-boundary.js:1264-1277.
    "euromecc.pending": Object.freeze({
      key: "euromecc.pending",
      boundaryEntryId: "firestore-euromecc-pending-root",
      datasetKey: "euromecc_pending",
      accessMode: "collection_root",
      collection: "euromecc_pending",
      sourceOfTruth: "registry v0.6 BOZZA + boundary firestore-euromecc-pending-root",
      matchStrategy: "euromecc_area_key_exact_match",
      viewBindings: Object.freeze(["Euromecc360", "Ricerca360"]),
      allowedFields: Object.freeze([
        "id",
        "__docId",
        "areaKey",
        "subKey",
        "title",
        "priority",
        "dueDate",
        "createdAt",
        "updatedAt",
      ]),
      forbiddenFields: Object.freeze([
        "note",
        "descrizione",
        "messaggio",
        "commento",
        "testo",
        "dettaglio",
        "rawText",
        "extractedText",
        "riepilogoBreve",
        "analisiCosti",
        "anomalie",
        "fornitoriNotevoli",
      ]),
      aliases: Object.freeze({}),
      requestLimits: Object.freeze({
        maxDocumentReadsPerRequest: 50,
        maxReturnedVehicleRecords: 50,
      }),
    }),
    // Boundary: internal-ai-firebase-readonly-boundary.js:1278-1294.
    "euromecc.done": Object.freeze({
      key: "euromecc.done",
      boundaryEntryId: "firestore-euromecc-done-root",
      datasetKey: "euromecc_done",
      accessMode: "collection_root",
      collection: "euromecc_done",
      sourceOfTruth: "registry v0.6 BOZZA + boundary firestore-euromecc-done-root",
      matchStrategy: "euromecc_area_key_exact_match",
      viewBindings: Object.freeze(["Euromecc360", "Ricerca360"]),
      allowedFields: Object.freeze([
        "id",
        "__docId",
        "areaKey",
        "subKey",
        "title",
        "doneDate",
        "nextDate",
        "closedPending",
        "createdAt",
        "updatedAt",
      ]),
      forbiddenFields: Object.freeze([
        "note",
        "descrizione",
        "messaggio",
        "commento",
        "testo",
        "dettaglio",
        "rawText",
        "extractedText",
        "riepilogoBreve",
        "analisiCosti",
        "anomalie",
        "fornitoriNotevoli",
        "by",
      ]),
      aliases: Object.freeze({}),
      requestLimits: Object.freeze({
        maxDocumentReadsPerRequest: 50,
        maxReturnedVehicleRecords: 50,
      }),
    }),
    // Boundary: internal-ai-firebase-readonly-boundary.js:1295-1311.
    "euromecc.issues": Object.freeze({
      key: "euromecc.issues",
      boundaryEntryId: "firestore-euromecc-issues-root",
      datasetKey: "euromecc_issues",
      accessMode: "collection_root",
      collection: "euromecc_issues",
      sourceOfTruth: "registry v0.6 BOZZA + boundary firestore-euromecc-issues-root",
      matchStrategy: "euromecc_area_key_exact_match",
      viewBindings: Object.freeze(["Euromecc360", "Ricerca360"]),
      allowedFields: Object.freeze([
        "id",
        "__docId",
        "areaKey",
        "subKey",
        "title",
        "check",
        "type",
        "state",
        "reportedAt",
        "closedDate",
        "createdAt",
        "updatedAt",
      ]),
      forbiddenFields: Object.freeze([
        "note",
        "descrizione",
        "messaggio",
        "commento",
        "testo",
        "dettaglio",
        "rawText",
        "extractedText",
        "riepilogoBreve",
        "analisiCosti",
        "anomalie",
        "fornitoriNotevoli",
        "reportedBy",
      ]),
      aliases: Object.freeze({}),
      requestLimits: Object.freeze({
        maxDocumentReadsPerRequest: 50,
        maxReturnedVehicleRecords: 50,
      }),
    }),
    // Boundary: internal-ai-firebase-readonly-boundary.js:1312-1328.
    "euromecc.areaMeta": Object.freeze({
      key: "euromecc.areaMeta",
      boundaryEntryId: "firestore-euromecc-area-meta-root",
      datasetKey: "euromecc_area_meta",
      accessMode: "collection_root",
      collection: "euromecc_area_meta",
      sourceOfTruth: "registry v0.6 BOZZA + boundary firestore-euromecc-area-meta-root",
      matchStrategy: "euromecc_area_key_exact_match",
      viewBindings: Object.freeze(["Euromecc360", "Ricerca360"]),
      allowedFields: Object.freeze([
        "id",
        "__docId",
        "areaKey",
        "cementType",
        "cementTypeShort",
        "updatedAt",
      ]),
      forbiddenFields: Object.freeze([
        "note",
        "descrizione",
        "messaggio",
        "commento",
        "testo",
        "dettaglio",
        "rawText",
        "extractedText",
        "riepilogoBreve",
        "analisiCosti",
        "anomalie",
        "fornitoriNotevoli",
        "updatedBy",
      ]),
      aliases: Object.freeze({}),
      requestLimits: Object.freeze({
        maxDocumentReadsPerRequest: 50,
        maxReturnedVehicleRecords: 50,
      }),
    }),
    // Boundary: internal-ai-firebase-readonly-boundary.js:1329-1342.
    "euromecc.extraComponents": Object.freeze({
      key: "euromecc.extraComponents",
      boundaryEntryId: "firestore-euromecc-extra-components-root",
      datasetKey: "euromecc_extra_components",
      accessMode: "collection_root",
      collection: "euromecc_extra_components",
      sourceOfTruth: "registry v0.6 BOZZA + boundary firestore-euromecc-extra-components-root",
      matchStrategy: "euromecc_area_or_component_key_exact_match",
      viewBindings: Object.freeze(["Euromecc360", "Ricerca360"]),
      allowedFields: Object.freeze([
        "id",
        "__docId",
        "areaKey",
        "subKey",
        "componentKey",
        "componentName",
        "title",
        "type",
        "state",
        "createdAt",
        "updatedAt",
      ]),
      forbiddenFields: Object.freeze([
        "note",
        "descrizione",
        "messaggio",
        "commento",
        "testo",
        "dettaglio",
        "rawText",
        "extractedText",
        "riepilogoBreve",
        "analisiCosti",
        "anomalie",
        "fornitoriNotevoli",
      ]),
      aliases: Object.freeze({}),
      requestLimits: Object.freeze({
        maxDocumentReadsPerRequest: 50,
        maxReturnedVehicleRecords: 50,
      }),
    }),
    // Boundary: internal-ai-firebase-readonly-boundary.js:1343-1356.
    "euromecc.relazioni": Object.freeze({
      key: "euromecc.relazioni",
      boundaryEntryId: "firestore-euromecc-relazioni-root",
      datasetKey: "euromecc_relazioni",
      accessMode: "collection_root",
      collection: "euromecc_relazioni",
      sourceOfTruth: "registry v0.6 BOZZA + boundary firestore-euromecc-relazioni-root",
      matchStrategy: "euromecc_relation_key_exact_match",
      viewBindings: Object.freeze(["Euromecc360", "Ricerca360"]),
      allowedFields: Object.freeze([
        "id",
        "__docId",
        "areaKey",
        "subKey",
        "relationKind",
        "tipo",
        "status",
        "stato",
        "sourceDocId",
        "targetDocId",
        "dataIntervento",
        "doneCount",
        "extraComponentsCount",
        "fileName",
        "fileSize",
        "fileStoragePath",
        "fileType",
        "ordineId",
        "ordineMateriali",
        "pendingCount",
        "statoImportazione",
        "createdAt",
        "updatedAt",
      ]),
      forbiddenFields: Object.freeze([
        "note",
        "descrizione",
        "messaggio",
        "commento",
        "testo",
        "dettaglio",
        "rawText",
        "extractedText",
        "riepilogoBreve",
        "analisiCosti",
        "anomalie",
        "fornitoriNotevoli",
      ]),
      aliases: Object.freeze({}),
      requestLimits: Object.freeze({
        maxDocumentReadsPerRequest: 50,
        maxReturnedVehicleRecords: 50,
      }),
    }),
  }),
});
