const F = (name, type, origin) => ({ name, type, origin });

const form = "form input";
const computed = "computed";
const prop = "prop";
const defaulted = "default";
const ia = "estrazione IA + correzione form";

export const AUDIT_METADATA = {
  date: "2026-04-30",
  title: "Audit Modali NEXT vs Firestore vs Tool Chat IA",
  mode: "AUDITOR FORENSE SISTEMICO",
  excludedScope: [
    "Archivista escluso per divieto esplicito del prompt.",
    "File .bak esclusi dalla lista modali attivi perche artefatti non-runtime.",
    "Pagine autisti/admin con bridge locale escluse quando il codice scrive solo overlay localStorage e non Firestore reale.",
  ],
};

export const MODAL_SPECS = [
  {
    id: "anagrafica-collega",
    modal: "NextAnagraficaModal (collega)",
    component: "NextAnagraficaModal",
    file: "src/next/components/NextAnagraficaModal.tsx",
    operations: ["create", "update", "delete"],
    writes: [
      {
        path: "storage/@colleghi",
        kind: "storageDoc",
        operation: "setDoc storage doc con array value",
        evidence: [
          { file: "src/next/components/NextAnagraficaModal.tsx", pattern: "savedId = await saveNextCollega" },
          { file: "src/next/nextAnagraficheWriter.ts", pattern: 'await setDoc(refDoc, { value }, { merge: true });' },
        ],
        fields: [
          F("id", "string", "form/id esistente o generated"),
          F("nome", "string", form),
          F("telefono", "string", form),
          F("telefonoPrivato", "string", form),
          F("badge", "string", form),
          F("descrizione", "string", form),
          F("codice", "string", form),
          F("pinSim", "string", form),
          F("pukSim", "string", form),
          F("schedeCarburante", "array<object>", form),
        ],
      },
    ],
  },
  {
    id: "anagrafica-fornitore",
    modal: "NextAnagraficaModal (fornitore)",
    component: "NextAnagraficaModal",
    file: "src/next/components/NextAnagraficaModal.tsx",
    operations: ["create", "update", "delete"],
    writes: [
      {
        path: "storage/@fornitori",
        kind: "storageDoc",
        operation: "setDoc storage doc con array value",
        evidence: [
          { file: "src/next/components/NextAnagraficaModal.tsx", pattern: "savedId = await saveNextFornitore" },
          { file: "src/next/nextAnagraficheWriter.ts", pattern: "export async function saveNextFornitore" },
        ],
        fields: [
          F("id", "string", "form/id esistente o generated"),
          F("nome", "string", form),
          F("telefono", "string", form),
          F("descrizione", "string", form),
        ],
      },
    ],
  },
  {
    id: "anagrafica-officina",
    modal: "NextAnagraficaModal (officina)",
    component: "NextAnagraficaModal",
    file: "src/next/components/NextAnagraficaModal.tsx",
    operations: ["create", "update", "delete"],
    writes: [
      {
        path: "storage/@officine",
        kind: "storageDoc",
        operation: "setDoc storage doc con array value",
        evidence: [
          { file: "src/next/components/NextAnagraficaModal.tsx", pattern: "savedId = await saveNextOfficina" },
          { file: "src/next/nextAnagraficheWriter.ts", pattern: "export async function saveNextOfficina" },
        ],
        fields: [
          F("id", "string", "form/id esistente o generated"),
          F("nome", "string", form),
          F("telefono", "string", form),
          F("telefoniAggiuntivi", "array<string>", form),
          F("descrizione", "string", form),
          F("citta", "string", form),
        ],
      },
    ],
  },
  {
    id: "mezzo-edit",
    modal: "NextMezzoEditModal",
    component: "NextMezzoEditModal",
    file: "src/next/components/NextMezzoEditModal.tsx",
    operations: ["update", "delete"],
    writes: [
      {
        path: "storage/@mezzi_aziendali",
        kind: "storageDoc",
        operation: "setItemSync array mezzi",
        evidence: [
          { file: "src/next/components/NextMezzoEditModal.tsx", pattern: "await updateNextMezzoAnagrafica" },
          { file: "src/next/nextMezziWriter.ts", pattern: "await writeMezziRecords(nextRecords);" },
        ],
        fields: [
          F("tipo", "string", form),
          F("categoria", "string", form),
          F("anno", "string|number", form),
          F("targa", "string", form),
          F("marca", "string", form),
          F("modello", "string", form),
          F("marcaModello", "string", computed),
          F("telaio", "string", form),
          F("colore", "string", form),
          F("cilindrata", "string", form),
          F("potenza", "string", form),
          F("massaComplessiva", "string", form),
          F("proprietario", "string", form),
          F("assicurazione", "string", form),
          F("dataImmatricolazione", "string", form),
          F("dataScadenzaRevisione", "string", form),
          F("dataUltimoCollaudo", "string", form),
          F("manutenzioneProgrammata", "boolean", form),
          F("manutenzioneDataInizio", "string", form),
          F("manutenzioneDataFine", "string", form),
          F("manutenzioneKmMax", "string", form),
          F("manutenzioneContratto", "string", form),
          F("note", "string", form),
          F("autistaId", "string|null", form),
          F("autistaNome", "string|null", computed),
        ],
      },
    ],
  },
  {
    id: "scadenze-prenotazione-collaudo",
    modal: "NextScadenzeCollaudiPage (prenotazione collaudo)",
    component: "NextScadenzeCollaudiPage",
    file: "src/next/NextScadenzeCollaudiPage.tsx",
    operations: ["create", "update", "delete"],
    writes: [
      {
        path: "storage/@mezzi_aziendali",
        kind: "storageDoc",
        operation: "setItemSync array mezzi",
        evidence: [
          { file: "src/next/NextScadenzeCollaudiPage.tsx", pattern: "await setPrenotazioneCollaudo" },
          { file: "src/next/nextScadenzeCollaudiWriter.ts", pattern: "prenotazioneCollaudo: nextPrenotazione" },
        ],
        fields: [
          F("prenotazioneCollaudo.data", "string", form),
          F("prenotazioneCollaudo.ora", "string", form),
          F("prenotazioneCollaudo.luogo", "string", form),
          F("prenotazioneCollaudo.note", "string", form),
        ],
      },
    ],
  },
  {
    id: "scadenze-pre-collaudo",
    modal: "NextScadenzeCollaudiPage (pre-collaudo)",
    component: "NextScadenzeCollaudiPage",
    file: "src/next/NextScadenzeCollaudiPage.tsx",
    operations: ["create", "update"],
    writes: [
      {
        path: "storage/@mezzi_aziendali",
        kind: "storageDoc",
        operation: "setItemSync array mezzi",
        evidence: [
          { file: "src/next/NextScadenzeCollaudiPage.tsx", pattern: "await setPreCollaudo" },
          { file: "src/next/nextScadenzeCollaudiWriter.ts", pattern: "preCollaudo: {" },
        ],
        fields: [
          F("preCollaudo.data", "string", form),
          F("preCollaudo.officina", "string", form),
          F("preCollaudo.lavoriPrevisti", "string", form),
        ],
      },
    ],
  },
  {
    id: "scadenze-revisione-completata",
    modal: "NextScadenzeCollaudiPage (revisione completata)",
    component: "NextScadenzeCollaudiPage",
    file: "src/next/NextScadenzeCollaudiPage.tsx",
    operations: ["update"],
    writes: [
      {
        path: "storage/@mezzi_aziendali",
        kind: "storageDoc",
        operation: "setItemSync array mezzi",
        evidence: [
          { file: "src/next/NextScadenzeCollaudiPage.tsx", pattern: "await markRevisioneCompletata" },
          { file: "src/next/nextScadenzeCollaudiWriter.ts", pattern: "dataUltimoCollaudo: revisioneDateValue" },
        ],
        fields: [
          F("dataUltimoCollaudo", "string", form),
          F("dataScadenzaRevisione", "string", computed),
          F("prenotazioneCollaudo.completata", "boolean", defaulted),
          F("prenotazioneCollaudo.completataIl", "string", form),
          F("prenotazioneCollaudo.esito", "string", form),
          F("prenotazioneCollaudo.noteEsito", "string", form),
          F("note", "string", computed),
        ],
      },
    ],
  },
  {
    id: "preventivo-manuale",
    modal: "NextPreventivoManualeModal",
    component: "NextPreventivoManualeModal",
    file: "src/next/NextPreventivoManualeModal.tsx",
    operations: ["create", "upload"],
    storageWrites: [{ path: "preventivi/manuali/{preventivoId}_{index}.{ext}", type: "image/pdf" }],
    writes: [
      {
        path: "storage/@preventivi",
        kind: "storageDoc",
        operation: "setDoc storage doc preventivi[]",
        evidence: [
          { file: "src/next/NextPreventivoManualeModal.tsx", pattern: "await saveAndUpsert" },
          { file: "src/next/nextPreventivoManualeWriter.ts", pattern: "await setDoc(" },
        ],
        fields: [
          F("id", "string", computed),
          F("fonte", "string", defaulted),
          F("fornitoreId", "string", form),
          F("fornitoreNome", "string", form),
          F("numeroPreventivo", "string", form),
          F("dataPreventivo", "string", form),
          F("righe", "array<object>", form),
          F("valuta", "string", form),
          F("imageStoragePaths", "array<string>", computed),
          F("imageUrls", "array<string>", computed),
          F("pdfStoragePath", "string|null", computed),
          F("pdfUrl", "string|null", computed),
          F("createdAt", "string", computed),
          F("updatedAt", "string", computed),
        ],
      },
      {
        path: "storage/@listino_prezzi",
        kind: "storageDoc",
        operation: "setDoc storage doc voci[]",
        evidence: [{ file: "src/next/nextPreventivoManualeWriter.ts", pattern: "await setDoc(listinoRef" }],
        fields: [
          F("id", "string", computed),
          F("fornitoreId", "string", form),
          F("fornitoreNome", "string", form),
          F("articoloCanonico", "string", form),
          F("codiceArticolo", "string", form),
          F("unita", "string", form),
          F("prezzoAttuale", "number", form),
          F("valuta", "string", form),
          F("preventivoId", "string", computed),
          F("updatedAt", "string", computed),
        ],
      },
    ],
  },
  {
    id: "preventivo-ia",
    modal: "NextPreventivoIaModal",
    component: "NextPreventivoIaModal",
    file: "src/next/NextPreventivoIaModal.tsx",
    operations: ["create", "upload"],
    storageWrites: [{ path: "preventivi/ia/{preventivoId}_{index}.{ext}", type: "image/pdf" }],
    writes: [
      {
        path: "storage/@preventivi",
        kind: "storageDoc",
        operation: "setDoc storage doc preventivi[]",
        evidence: [
          { file: "src/next/NextPreventivoIaModal.tsx", pattern: "await saveAndUpsert" },
          { file: "src/next/nextPreventivoManualeWriter.ts", pattern: "saveNextPreventivoManuale" },
        ],
        fields: [
          F("id", "string", computed),
          F("fonte", "string", defaulted),
          F("fornitoreId", "string", ia),
          F("fornitoreNome", "string", ia),
          F("numeroPreventivo", "string", ia),
          F("dataPreventivo", "string", ia),
          F("righe", "array<object>", ia),
          F("valuta", "string", ia),
          F("imageStoragePaths", "array<string>", computed),
          F("imageUrls", "array<string>", computed),
          F("pdfStoragePath", "string|null", computed),
          F("pdfUrl", "string|null", computed),
          F("createdAt", "string", computed),
          F("updatedAt", "string", computed),
        ],
      },
      {
        path: "storage/@listino_prezzi",
        kind: "storageDoc",
        operation: "setDoc storage doc voci[]",
        evidence: [{ file: "src/next/nextPreventivoManualeWriter.ts", pattern: "upsertListinoFromPreventivoManuale" }],
        fields: [
          F("id", "string", computed),
          F("fornitoreId", "string", ia),
          F("fornitoreNome", "string", ia),
          F("articoloCanonico", "string", ia),
          F("codiceArticolo", "string", ia),
          F("unita", "string", ia),
          F("prezzoAttuale", "number", ia),
          F("valuta", "string", ia),
          F("preventivoId", "string", computed),
          F("updatedAt", "string", computed),
        ],
      },
    ],
  },
  {
    id: "chat-ia-report-archive",
    modal: "ChatIaReportModal",
    component: "ChatIaReportModal",
    file: "src/next/chat-ia/components/ChatIaReportModal.tsx",
    operations: ["create", "upload", "delete"],
    storageWrites: [{ path: "chat_ia_reports/{sector}/{year}/{id}.pdf", type: "application/pdf" }],
    writes: [
      {
        path: "chat_ia_reports",
        kind: "collection",
        operation: "setDoc/updateDoc root collection",
        evidence: [
          { file: "src/next/chat-ia/components/ChatIaReportModal.tsx", pattern: "await createChatIaReportArchiveEntry" },
          { file: "src/next/chat-ia/reports/chatIaReportArchive.ts", pattern: "await setDoc(docRef, payload);" },
        ],
        fields: [
          F("version", "number", defaulted),
          F("status", "string", defaulted),
          F("prompt", "string", prop),
          F("title", "string", prop),
          F("sector", "string", prop),
          F("targetKind", "string", prop),
          F("targetValue", "string", prop),
          F("periodFrom", "string|null", prop),
          F("periodTo", "string|null", prop),
          F("summary", "string|null", prop),
          F("blocks", "array<object>", prop),
          F("pdfUrl", "string", computed),
          F("pdfStoragePath", "string", computed),
          F("createdAt", "string", computed),
          F("updatedAt", "string", computed),
          F("meta", "object", prop),
          F("deletedAt", "string", computed),
        ],
      },
    ],
  },
  {
    id: "attrezzature-cantieri",
    modal: "NextAttrezzatureCantieriWritePanel",
    component: "NextAttrezzatureCantieriWritePanel",
    file: "src/next/NextAttrezzatureCantieriWritePanel.tsx",
    operations: ["create", "update", "delete", "upload"],
    storageWrites: [{ path: "attrezzature/{movimentoId}-{timestamp}.{ext}", type: "image" }],
    writes: [
      {
        path: "storage/@attrezzature_cantieri",
        kind: "storageDoc",
        operation: "setDoc storage doc value[]",
        evidence: [
          { file: "src/next/NextAttrezzatureCantieriWritePanel.tsx", pattern: "await createMovimentoAttrezzatura" },
          { file: "src/next/nextAttrezzatureCantieriWriter.ts", pattern: "await writeMovimenti" },
        ],
        fields: [
          F("id", "string", computed),
          F("tipo", "string", form),
          F("data", "string", form),
          F("materialeCategoria", "string", form),
          F("descrizione", "string", form),
          F("quantita", "number", form),
          F("unita", "string", form),
          F("cantiereId", "string", form),
          F("cantiereLabel", "string", form),
          F("note", "string|null", form),
          F("fotoUrl", "string|null", computed),
          F("fotoStoragePath", "string|null", computed),
          F("sourceCantiereId", "string|null", form),
          F("sourceCantiereLabel", "string|null", form),
        ],
      },
    ],
  },
  {
    id: "manutenzioni-save",
    modal: "NextManutenzioniPage (form manutenzione)",
    component: "NextManutenzioniPage",
    file: "src/next/NextManutenzioniPage.tsx",
    operations: ["create", "update"],
    writes: [
      {
        path: "storage/@manutenzioni",
        kind: "storageDoc",
        operation: "setItemSync storico manutenzioni",
        evidence: [
          { file: "src/next/NextManutenzioniPage.tsx", pattern: "await saveNextManutenzioneBusinessRecord" },
          { file: "src/next/domain/nextManutenzioniDomain.ts", pattern: "await setItemSync(MANUTENZIONI_KEY, nextStorico);" },
        ],
        fields: [
          F("id", "string", computed),
          F("targa", "string", form),
          F("tipo", "string", form),
          F("fornitore", "string|null", form),
          F("km", "number|null", form),
          F("ore", "number|null", form),
          F("sottotipo", "string|null", form),
          F("descrizione", "string", form),
          F("eseguito", "string|null", form),
          F("data", "string", form),
          F("materiali", "array<object>", form),
          F("importo", "number|null", form),
          F("gommeInterventoTipo", "string", form),
          F("gommeStraordinario", "object", form),
          F("assiCoinvolti", "array<string>", form),
          F("gommePerAsse", "array<object>", form),
          F("sourceDocumentId", "string", prop),
        ],
      },
      {
        path: "storage/@inventario",
        kind: "storageDoc",
        operation: "setItemSync side effect materiali",
        evidence: [{ file: "src/next/domain/nextManutenzioniDomain.ts", pattern: "await setItemSync(INVENTARIO_KEY, inventarioAggiornato);" }],
        fields: [F("quantita", "number", computed), F("quantitaTotale", "number", computed), F("stockKey", "string|null", computed)],
      },
      {
        path: "storage/@materialiconsegnati",
        kind: "storageDoc",
        operation: "setItemSync side effect materiali",
        evidence: [{ file: "src/next/domain/nextManutenzioniDomain.ts", pattern: "await setItemSync(MATERIALI_CONSEGNATI_KEY, materialiConsegnatiAggiornati);" }],
        fields: [
          F("id", "string", computed),
          F("tipo", "string", defaulted),
          F("direzione", "string", defaulted),
          F("data", "string", form),
          F("materialeId", "string", form),
          F("inventarioRefId", "string", form),
          F("materialeLabel", "string", form),
          F("descrizione", "string", form),
          F("quantita", "number", form),
          F("unita", "string", form),
          F("origine", "string", defaulted),
          F("targa", "string", form),
          F("mezzoTarga", "string", form),
          F("fornitore", "string", computed),
          F("stockKey", "string|null", computed),
          F("destinatario", "object", computed),
          F("motivo", "string", defaulted),
        ],
      },
    ],
  },
  {
    id: "manutenzioni-delete",
    modal: "NextManutenzioniPage (eliminazione manutenzione)",
    component: "NextManutenzioniPage",
    file: "src/next/NextManutenzioniPage.tsx",
    operations: ["delete"],
    writes: [
      {
        path: "storage/@manutenzioni",
        kind: "storageDoc",
        operation: "setItemSync remove record",
        evidence: [{ file: "src/next/NextManutenzioniPage.tsx", pattern: "await deleteNextManutenzioneBusinessRecord" }],
        fields: [F("id", "string", prop)],
      },
      {
        path: "storage/@inventario",
        kind: "storageDoc",
        operation: "setItemSync restore quantity",
        evidence: [{ file: "src/next/domain/nextManutenzioniDomain.ts", pattern: "await setItemSync(INVENTARIO_KEY, inventarioAggiornato);" }],
        fields: [F("quantita", "number", computed), F("quantitaTotale", "number", computed)],
      },
      {
        path: "storage/@materialiconsegnati",
        kind: "storageDoc",
        operation: "setItemSync remove movement",
        evidence: [{ file: "src/next/domain/nextManutenzioniDomain.ts", pattern: "await setItemSync(MATERIALI_CONSEGNATI_KEY, consegneAggiornate);" }],
        fields: [F("id", "string", prop), F("motivo", "string", prop), F("destinatario.refId", "string", prop)],
      },
    ],
  },
  {
    id: "lavori-create-group",
    modal: "NextLavoriDaEseguirePage (gruppo lavori)",
    component: "NextLavoriDaEseguirePage",
    file: "src/next/NextLavoriDaEseguirePage.tsx",
    operations: ["create"],
    writes: [
      {
        path: "storage/@lavori",
        kind: "storageDoc",
        operation: "setItemSync lavori[]",
        evidence: [{ file: "src/next/NextLavoriDaEseguirePage.tsx", pattern: "await setItemSync(LAVORI_KEY, nuovi);" }],
        fields: [
          F("id", "string", computed),
          F("gruppoId", "string", computed),
          F("tipo", "string", form),
          F("targa", "string", form),
          F("descrizione", "string", form),
          F("dataInserimento", "string", form),
          F("eseguito", "boolean", defaulted),
          F("urgenza", "string", form),
          F("segnalatoDa", "string", defaulted),
          F("sottoElementi", "array", defaulted),
        ],
      },
    ],
  },
  {
    id: "lavori-detail-modifica",
    modal: "NextDettaglioLavoroPage (modifica lavoro)",
    component: "NextDettaglioLavoroPage",
    file: "src/next/NextDettaglioLavoroPage.tsx",
    operations: ["update"],
    writes: [
      {
        path: "storage/@lavori",
        kind: "storageDoc",
        operation: "setItemSync lavori[]",
        evidence: [{ file: "src/next/NextDettaglioLavoroPage.tsx", pattern: "await setItemSync(LAVORI_KEY, nextItems);" }],
        fields: [F("descrizione", "string", form), F("dataInserimento", "string", form)],
      },
    ],
  },
  {
    id: "lavori-detail-esegui",
    modal: "NextDettaglioLavoroPage (esegui lavoro)",
    component: "NextDettaglioLavoroPage",
    file: "src/next/NextDettaglioLavoroPage.tsx",
    operations: ["update"],
    writes: [
      {
        path: "storage/@lavori",
        kind: "storageDoc",
        operation: "setItemSync lavori[]",
        evidence: [{ file: "src/next/NextDettaglioLavoroPage.tsx", pattern: "dataEsecuzione: new Date().toISOString()" }],
        fields: [
          F("eseguito", "boolean", defaulted),
          F("chiHaEseguito", "string", form),
          F("dataEsecuzione", "string", computed),
        ],
      },
    ],
  },
  {
    id: "lavori-detail-delete",
    modal: "NextDettaglioLavoroPage (elimina lavoro)",
    component: "NextDettaglioLavoroPage",
    file: "src/next/NextDettaglioLavoroPage.tsx",
    operations: ["delete"],
    writes: [
      {
        path: "storage/@lavori",
        kind: "storageDoc",
        operation: "setItemSync remove record",
        evidence: [{ file: "src/next/NextDettaglioLavoroPage.tsx", pattern: "const nextItems = lavori.filter" }],
        fields: [F("id", "string", prop)],
      },
    ],
  },
  {
    id: "mappa-storico-foto",
    modal: "NextMappaStoricoPage (upload foto vista)",
    component: "NextMappaStoricoPage",
    file: "src/next/NextMappaStoricoPage.tsx",
    operations: ["create", "upload"],
    storageWrites: [{ path: "mezzi_foto/{TARGA}/{vista}_{uploadedAt}.{ext}", type: "image" }],
    writes: [
      {
        path: "storage/@mezzi_foto_viste",
        kind: "storageDoc",
        operation: "setItemSync foto vista",
        evidence: [{ file: "src/next/domain/nextMappaStoricoDomain.ts", pattern: "await setItemSync(FOTO_VISTE_KEY" }],
        fields: [
          F("id", "string", computed),
          F("targa", "string", prop),
          F("vista", "string", form),
          F("storagePath", "string", computed),
          F("downloadUrl", "string", computed),
          F("fileName", "string", form),
          F("contentType", "string|null", form),
          F("uploadedAt", "number", computed),
        ],
      },
    ],
  },
  {
    id: "mappa-storico-hotspot",
    modal: "NextMappaStoricoPage (hotspot mappa)",
    component: "NextMappaStoricoPage",
    file: "src/next/NextMappaStoricoPage.tsx",
    operations: ["create", "delete"],
    writes: [
      {
        path: "storage/@mezzi_hotspot_mapping",
        kind: "storageDoc",
        operation: "setItemSync hotspot[]",
        evidence: [{ file: "src/next/domain/nextMappaStoricoDomain.ts", pattern: "await setItemSync(HOTSPOT_MAPPING_KEY" }],
        fields: [
          F("id", "string", computed),
          F("targa", "string", prop),
          F("vista", "string", form),
          F("areaId", "string", form),
          F("x", "number", computed),
          F("y", "number", computed),
          F("createdAt", "number", computed),
        ],
      },
    ],
  },
  {
    id: "ia-libretto-save",
    modal: "NextIALibrettoPage (salva libretto)",
    component: "NextIALibrettoPage",
    file: "src/next/NextIALibrettoPage.tsx",
    operations: ["create", "update", "upload"],
    storageWrites: [{ path: "mezzi_aziendali/{mezzoId}/libretto.jpg", type: "image/data_url" }],
    writes: [
      {
        path: "storage/@mezzi_aziendali",
        kind: "storageDoc",
        operation: "setItemSync mezzi[]",
        evidence: [{ file: "src/next/NextIALibrettoPage.tsx", pattern: 'await setItemSync("@mezzi_aziendali", mezzi);' }],
        fields: [
          F("id", "string", computed),
          F("tipo", "string", defaulted),
          F("categoria", "string", ia),
          F("targa", "string", ia),
          F("marca", "string", ia),
          F("modello", "string", ia),
          F("marcaModello", "string", computed),
          F("telaio", "string", ia),
          F("colore", "string", ia),
          F("cilindrata", "string", ia),
          F("potenza", "string", ia),
          F("massaComplessiva", "string", ia),
          F("proprietario", "string", ia),
          F("assicurazione", "string", ia),
          F("dataImmatricolazione", "string", ia),
          F("dataUltimoCollaudo", "string", ia),
          F("dataScadenzaRevisione", "string", ia),
          F("note", "string", ia),
          F("anno", "string", computed),
          F("librettoUrl", "string", computed),
          F("librettoStoragePath", "string", computed),
        ],
      },
    ],
  },
  {
    id: "magazzino-inventario",
    modal: "NextMagazzinoPage (inventario)",
    component: "NextMagazzinoPage",
    file: "src/next/NextMagazzinoPage.tsx",
    operations: ["create", "update", "delete", "upload"],
    storageWrites: [{ path: "inventario/{itemId}/foto.{ext}", type: "image" }],
    writes: [
      {
        path: "storage/@inventario",
        kind: "storageDoc",
        operation: "setItemSync inventario[]",
        evidence: [{ file: "src/next/NextMagazzinoPage.tsx", pattern: "async function persistInventario" }],
        fields: [
          F("id", "string", computed),
          F("descrizione", "string", form),
          F("quantita", "number", form),
          F("quantitaTotale", "number", computed),
          F("unita", "string", form),
          F("stockKey", "string|null", computed),
          F("stockLoadKeys", "array<string>", computed),
          F("fotoUrl", "string|null", computed),
          F("fotoStoragePath", "string|null", computed),
          F("fornitore", "string|null", form),
          F("fornitoreLabel", "string|null", form),
          F("nomeFornitore", "string|null", form),
          F("sogliaMinima", "number", form),
        ],
      },
    ],
  },
  {
    id: "magazzino-consegna",
    modal: "NextMagazzinoPage (consegna materiale)",
    component: "NextMagazzinoPage",
    file: "src/next/NextMagazzinoPage.tsx",
    operations: ["create", "delete", "update"],
    writes: [
      {
        path: "storage/@materialiconsegnati",
        kind: "storageDoc",
        operation: "setItemSync consegne[]",
        evidence: [{ file: "src/next/NextMagazzinoPage.tsx", pattern: "async function persistConsegne" }],
        fields: [
          F("id", "string", computed),
          F("descrizione", "string", form),
          F("materiale", "string", form),
          F("materialeLabel", "string", form),
          F("quantita", "number", form),
          F("unita", "string", form),
          F("destinatario", "object", form),
          F("target", "string", computed),
          F("motivo", "string|null", form),
          F("data", "string", form),
          F("fornitore", "string|null", computed),
          F("inventarioRefId", "string|null", computed),
          F("stockKey", "string|null", computed),
          F("direzione", "string", defaulted),
          F("tipo", "string", defaulted),
          F("origine", "string", defaulted),
          F("mezzoTarga", "string|null", computed),
          F("targa", "string|null", computed),
        ],
      },
      {
        path: "storage/@inventario",
        kind: "storageDoc",
        operation: "setItemSync stock side effect",
        evidence: [{ file: "src/next/NextMagazzinoPage.tsx", pattern: "await persistInventario(nuovaListaInventario);" }],
        fields: [F("quantita", "number", computed)],
      },
    ],
  },
  {
    id: "magazzino-adblue-cambio",
    modal: "NextMagazzinoPage (cambio cisterna AdBlue)",
    component: "NextMagazzinoPage",
    file: "src/next/NextMagazzinoPage.tsx",
    operations: ["create", "update"],
    writes: [
      {
        path: "storage/@cisterne_adblue",
        kind: "storageDoc",
        operation: "setItemSync cambi[]",
        evidence: [{ file: "src/next/NextMagazzinoPage.tsx", pattern: "async function persistCambi" }],
        fields: [
          F("id", "string", computed),
          F("data", "string", form),
          F("quantitaLitri", "number", form),
          F("quantita", "number", form),
          F("litri", "number", form),
          F("inventarioRefId", "string|null", computed),
          F("stockKey", "string|null", computed),
          F("materialeLabel", "string", defaulted),
          F("descrizione", "string", defaulted),
          F("unita", "string", defaulted),
          F("numeroCisterna", "string|null", form),
          F("note", "string|null", form),
        ],
      },
      {
        path: "storage/@inventario",
        kind: "storageDoc",
        operation: "setItemSync scarico AdBlue",
        evidence: [{ file: "src/next/NextMagazzinoPage.tsx", pattern: "await persistInventario(inventarioAggiornato);" }],
        fields: [F("quantita", "number", computed)],
      },
    ],
  },
  {
    id: "magazzino-consolidamenti",
    modal: "NextMagazzinoPage (consolidamento documenti/arrivi)",
    component: "NextMagazzinoPage",
    file: "src/next/NextMagazzinoPage.tsx",
    operations: ["update"],
    writes: [
      {
        path: "storage/@inventario",
        kind: "storageDoc",
        operation: "setItemSync inventario[] da fatture/arrivi",
        evidence: [{ file: "src/next/NextMagazzinoPage.tsx", pattern: "handleCaricaArrivoInInventario" }],
        fields: [
          F("quantita", "number", computed),
          F("unita", "string", computed),
          F("stockKey", "string|null", computed),
          F("stockLoadKeys", "array<string>", computed),
          F("fornitore", "string|null", computed),
        ],
      },
    ],
  },
  {
    id: "materiali-ordine-create",
    modal: "NextMaterialiDaOrdinarePage (crea ordine)",
    component: "NextMaterialiDaOrdinarePage",
    file: "src/next/NextMaterialiDaOrdinarePage.tsx",
    operations: ["create", "upload"],
    storageWrites: [{ path: "materiali/{id}-{timestamp}.{ext}", type: "image" }],
    writes: [
      {
        path: "storage/@ordini",
        kind: "storageDoc",
        operation: "setDoc storage doc value[]",
        evidence: [{ file: "src/next/NextMaterialiDaOrdinarePage.tsx", pattern: "const nuovoOrdine: Ordine" }],
        fields: [
          F("id", "string", computed),
          F("idFornitore", "string", form),
          F("nomeFornitore", "string", form),
          F("dataOrdine", "string", computed),
          F("materiali", "array<object>", form),
          F("materiali[].id", "string", form),
          F("materiali[].descrizione", "string", form),
          F("materiali[].quantita", "number", form),
          F("materiali[].unita", "string", form),
          F("materiali[].arrivato", "boolean", defaulted),
          F("materiali[].fotoUrl", "string|null", computed),
          F("materiali[].fotoStoragePath", "string|null", computed),
          F("arrivato", "boolean", defaulted),
        ],
      },
    ],
  },
  {
    id: "procurement-order-detail",
    modal: "NextProcurementReadOnlyPanel (dettaglio ordine)",
    component: "NextProcurementReadOnlyPanel",
    file: "src/next/NextProcurementReadOnlyPanel.tsx",
    operations: ["update", "delete", "upload"],
    storageWrites: [{ path: "materiali/{id}-{timestamp}.{ext}", type: "image" }],
    writes: [
      {
        path: "storage/@ordini",
        kind: "storageDoc",
        operation: "setDoc storage doc value[]",
        evidence: [{ file: "src/next/NextProcurementReadOnlyPanel.tsx", pattern: "const ordineFirestore = {" }],
        fields: [
          F("id", "string", prop),
          F("idFornitore", "string", prop),
          F("nomeFornitore", "string", prop),
          F("dataOrdine", "string", prop),
          F("materiali", "array<object>", form),
          F("materiali[].id", "string", form),
          F("materiali[].descrizione", "string", form),
          F("materiali[].quantita", "number", form),
          F("materiali[].unita", "string", form),
          F("materiali[].arrivato", "boolean", form),
          F("materiali[].dataArrivo", "string|null", form),
          F("materiali[].fotoUrl", "string|null", computed),
          F("materiali[].fotoStoragePath", "string|null", computed),
          F("materiali[].note", "string|null", form),
          F("materiali[].prezzoUnitario", "number|null", form),
          F("materiali[].valuta", "string|null", form),
          F("materiali[].unitaPrezzo", "string|null", form),
          F("arrivato", "boolean", computed),
          F("ordineNote", "string|null", form),
        ],
      },
    ],
  },
  {
    id: "ia-documenti-currency",
    modal: "NextIADocumentiPage (modifica valuta)",
    component: "NextIADocumentiPage",
    file: "src/next/NextIADocumentiPage.tsx",
    operations: ["update"],
    writes: [
      {
        path: "@documenti_mezzi",
        kind: "collection",
        operation: "updateDoc root collection",
        evidence: [{ file: "src/next/domain/nextDocumentiCostiDomain.ts", pattern: "await updateDoc(doc(db, sourceKey, normalizedId), {" }],
        fields: [F("currency", "string", form), F("valuta", "string", form)],
      },
      {
        path: "@documenti_magazzino",
        kind: "collection",
        operation: "updateDoc root collection",
        evidence: [{ file: "src/next/domain/nextDocumentiCostiDomain.ts", pattern: "sourceKey === \"@documenti_magazzino\"" }],
        fields: [F("currency", "string", form), F("valuta", "string", form)],
      },
      {
        path: "@documenti_generici",
        kind: "collection",
        operation: "updateDoc root collection",
        evidence: [{ file: "src/next/domain/nextDocumentiCostiDomain.ts", pattern: "sourceKey === \"@documenti_generici\"" }],
        fields: [F("currency", "string", form), F("valuta", "string", form)],
      },
      {
        path: "storage/@costiMezzo",
        kind: "storageDoc",
        operation: "setItemSync storage doc",
        evidence: [{ file: "src/next/domain/nextDocumentiCostiDomain.ts", pattern: "await setItemSync(COSTI_DATASET_KEY, nextItems);" }],
        fields: [F("currency", "string", form), F("valuta", "string", form)],
      },
    ],
  },
  {
    id: "ia-documenti-delete",
    modal: "NextIADocumentiPage (elimina documento)",
    component: "NextIADocumentiPage",
    file: "src/next/NextIADocumentiPage.tsx",
    operations: ["delete"],
    writes: [
      { path: "@documenti_mezzi", kind: "collection", operation: "deleteDoc root collection", evidence: [{ file: "src/next/NextIADocumentiPage.tsx", pattern: "deleteNextDocumentoCosto" }], fields: [F("sourceDocId", "string", prop)] },
      { path: "@documenti_magazzino", kind: "collection", operation: "deleteDoc root collection", evidence: [{ file: "src/next/domain/nextDocumentiCostiDomain.ts", pattern: "await deleteDoc(doc(db, sourceKey, normalizedId));" }], fields: [F("sourceDocId", "string", prop)] },
      { path: "@documenti_generici", kind: "collection", operation: "deleteDoc root collection", evidence: [{ file: "src/next/domain/nextDocumentiCostiDomain.ts", pattern: "await deleteDoc(doc(db, sourceKey, normalizedId));" }], fields: [F("sourceDocId", "string", prop)] },
      { path: "storage/@costiMezzo", kind: "storageDoc", operation: "setItemSync filtered array", evidence: [{ file: "src/next/domain/nextDocumentiCostiDomain.ts", pattern: "const nextItems = items.filter" }], fields: [F("sourceDocId", "string", prop)] },
    ],
  },
  {
    id: "dossier-delete-fattura",
    modal: "NextDossierMezzoPage (elimina fattura)",
    component: "NextDossierMezzoPage",
    file: "src/next/NextDossierMezzoPage.tsx",
    operations: ["delete"],
    writes: [
      { path: "@documenti_mezzi", kind: "collection", operation: "deleteDoc root collection", evidence: [{ file: "src/next/NextDossierMezzoPage.tsx", pattern: "deleteNextDocumentoCosto(fatturaToDelete)" }], fields: [F("sourceDocId", "string", prop)] },
      { path: "@documenti_magazzino", kind: "collection", operation: "deleteDoc root collection", evidence: [{ file: "src/next/domain/nextDocumentiCostiDomain.ts", pattern: "sourceKey === \"@documenti_magazzino\"" }], fields: [F("sourceDocId", "string", prop)] },
      { path: "@documenti_generici", kind: "collection", operation: "deleteDoc root collection", evidence: [{ file: "src/next/domain/nextDocumentiCostiDomain.ts", pattern: "sourceKey === \"@documenti_generici\"" }], fields: [F("sourceDocId", "string", prop)] },
      { path: "storage/@costiMezzo", kind: "storageDoc", operation: "setItemSync filtered array", evidence: [{ file: "src/next/domain/nextDocumentiCostiDomain.ts", pattern: "sourceKey === COSTI_DATASET_KEY" }], fields: [F("sourceDocId", "string", prop)] },
    ],
  },
  {
    id: "cisterna-cambio",
    modal: "NextCisternaPage (cambio EUR/CHF)",
    component: "NextCisternaPage",
    file: "src/next/NextCisternaPage.tsx",
    operations: ["update"],
    writes: [
      {
        path: "@cisterna_parametri_mensili",
        kind: "collection",
        operation: "setDoc doc @cisterna_parametri_mensili/{monthKey}",
        evidence: [{ file: "src/next/nextCisternaWriter.ts", pattern: "saveNextCisternaMonthlyExchange" }],
        fields: [F("mese", "string", computed), F("cambioEurChf", "number|null", form), F("updatedAt", "Timestamp", computed)],
      },
    ],
  },
  {
    id: "cisterna-duplicati",
    modal: "NextCisternaPage (scelta duplicato)",
    component: "NextCisternaPage",
    file: "src/next/NextCisternaPage.tsx",
    operations: ["update"],
    writes: [
      {
        path: "@documenti_cisterna",
        kind: "collection",
        operation: "updateDoc documenti duplicati",
        evidence: [{ file: "src/next/nextCisternaWriter.ts", pattern: "updateNextCisternaDuplicateChoice" }],
        fields: [
          F("dupGroupKey", "string", computed),
          F("dupChosen", "boolean", computed),
          F("dupIgnored", "boolean", computed),
          F("updatedAt", "Timestamp", computed),
        ],
      },
    ],
  },
  {
    id: "cisterna-documento-ia",
    modal: "NextCisternaIAPage (documento IA)",
    component: "NextCisternaIAPage",
    file: "src/next/NextCisternaIAPage.tsx",
    operations: ["create", "upload"],
    storageWrites: [{ path: "documenti_pdf/cisterna/{yyyy}/{mm}/{timestamp}_{safeName}", type: "pdf/image" }],
    writes: [
      {
        path: "@documenti_cisterna",
        kind: "collection",
        operation: "addDoc root collection",
        evidence: [{ file: "src/next/NextCisternaIAPage.tsx", pattern: "const payload = sanitizeForFirestore" }],
        fields: [
          F("tipoDocumento", "string", ia),
          F("fornitore", "string|null", ia),
          F("destinatario", "string|null", ia),
          F("numeroDocumento", "string|null", ia),
          F("dataDocumento", "string|null", ia),
          F("yearMonth", "string", computed),
          F("mese", "string", computed),
          F("litriTotali", "number|null", ia),
          F("litri15C", "number|null", ia),
          F("totaleDocumento", "number|null", ia),
          F("valuta", "string|null", ia),
          F("currency", "string|null", ia),
          F("prodotto", "string|null", ia),
          F("testo", "string|null", ia),
          F("daVerificare", "boolean", computed),
          F("motivoVerifica", "string|null", computed),
          F("fileUrl", "string", computed),
          F("storagePath", "string|null", computed),
          F("nomeFile", "string|null", form),
          F("fonte", "string", defaulted),
          F("createdAt", "Timestamp", computed),
          F("iaEngine", "string", defaulted),
        ],
      },
    ],
  },
  {
    id: "cisterna-schede-crop",
    modal: "NextCisternaSchedeTestPage (upload ritaglio scheda)",
    component: "NextCisternaSchedeTestPage",
    file: "src/next/NextCisternaSchedeTestPage.tsx",
    operations: ["upload"],
    storageWrites: [{ path: "documenti_pdf/cisterna_schede/{yyyy}/{mm}/{timestamp}_{safeName}_crop.jpg", type: "image/jpeg" }],
    writes: [],
  },
  {
    id: "cisterna-schede-save",
    modal: "NextCisternaSchedeTestPage (salva scheda)",
    component: "NextCisternaSchedeTestPage",
    file: "src/next/NextCisternaSchedeTestPage.tsx",
    operations: ["create", "update"],
    storageWrites: [{ path: "documenti_pdf/cisterna_schede/{yyyy}/{mm}/{timestamp}_{safeName}_crop.jpg", type: "image/jpeg", optional: true }],
    writes: [
      {
        path: "@cisterna_schede_ia",
        kind: "collection",
        operation: "addDoc/updateDoc root collection",
        evidence: [{ file: "src/next/NextCisternaSchedeTestPage.tsx", pattern: "await createNextCisternaSchedaRecord" }],
        fields: [
          F("source", "string", form),
          F("rowCount", "number", computed),
          F("rows", "array<object>", ia),
          F("needsReview", "boolean", computed),
          F("yearMonth", "string", computed),
          F("fileUrl", "string|null", computed),
          F("storagePath", "string|null", computed),
          F("nomeFile", "string|null", form),
          F("rawLines", "array<string>", ia),
          F("summary", "object", computed),
          F("fonte", "string", defaulted),
          F("iaEngine", "string", defaulted),
          F("createdAt", "Timestamp", computed),
          F("updatedAt", "Timestamp", computed),
        ],
      },
    ],
  },
  {
    id: "euromecc-relazione-bozza",
    modal: "NextEuromeccPage (relazione bozza)",
    component: "NextEuromeccPage",
    file: "src/next/NextEuromeccPage.tsx",
    operations: ["create"],
    writes: [
      {
        path: "euromecc_relazioni",
        kind: "collection",
        operation: "addDoc root collection",
        evidence: [{ file: "src/next/NextEuromeccPage.tsx", pattern: "async function handleSaveBozza" }],
        fields: [
          F("fileName", "string", form),
          F("fileType", "string", form),
          F("dataIntervento", "string", ia),
          F("tecnici", "array", ia),
          F("note", "string", form),
          F("statoImportazione", "string", defaulted),
          F("doneCount", "number", defaulted),
          F("pendingCount", "number", defaulted),
          F("extraComponentsCount", "number", defaulted),
          F("createdAt", "Timestamp", computed),
          F("updatedAt", "Timestamp", computed),
        ],
      },
    ],
  },
  {
    id: "euromecc-relazione-confermata",
    modal: "NextEuromeccPage (relazione confermata)",
    component: "NextEuromeccPage",
    file: "src/next/NextEuromeccPage.tsx",
    operations: ["create", "upload"],
    storageWrites: [{ path: "euromecc/relazioni/{uploadRelazioneId}/{timestamp}_{fileName}", type: "pdf/image" }],
    writes: [
      {
        path: "euromecc_relazioni",
        kind: "collection",
        operation: "addDoc root collection",
        evidence: [{ file: "src/next/NextEuromeccPage.tsx", pattern: "async function handleConferma" }],
        fields: [
          F("fileName", "string", form),
          F("fileType", "string", form),
          F("dataIntervento", "string", ia),
          F("tecnici", "array", ia),
          F("note", "string", form),
          F("statoImportazione", "string", defaulted),
          F("doneCount", "number", computed),
          F("pendingCount", "number", computed),
          F("extraComponentsCount", "number", computed),
          F("fileUrl", "string|null", computed),
          F("fileStoragePath", "string|null", computed),
          F("fileSize", "number|null", computed),
          F("createdAt", "Timestamp", computed),
          F("updatedAt", "Timestamp", computed),
        ],
      },
      {
        path: "euromecc_done",
        kind: "collection",
        operation: "addDoc root collection",
        evidence: [{ file: "src/next/NextEuromeccPage.tsx", pattern: "await addEuromeccDoneTask" }],
        fields: [F("areaKey", "string", ia), F("subKey", "string", ia), F("title", "string", ia), F("doneDate", "string", ia), F("by", "string", ia), F("note", "string", ia), F("nextDate", "string|null", ia), F("closedPending", "boolean", defaulted), F("createdAt", "Timestamp", computed), F("updatedAt", "Timestamp", computed)],
      },
      {
        path: "euromecc_pending",
        kind: "collection",
        operation: "addDoc root collection",
        evidence: [{ file: "src/next/NextEuromeccPage.tsx", pattern: "await addEuromeccPendingTask" }],
        fields: [F("areaKey", "string", ia), F("subKey", "string", ia), F("title", "string", ia), F("priority", "string", ia), F("dueDate", "string", ia), F("note", "string", ia), F("createdAt", "Timestamp", computed), F("updatedAt", "Timestamp", computed)],
      },
      {
        path: "euromecc_extra_components",
        kind: "collection",
        operation: "addDoc root collection",
        evidence: [{ file: "src/next/NextEuromeccPage.tsx", pattern: 'collection(db, "euromecc_extra_components")' }],
        fields: [F("areaKey", "string", ia), F("subKey", "string", computed), F("name", "string", ia), F("code", "string", ia), F("addedFrom", "string", computed), F("addedAt", "string", computed), F("addedBy", "string", ia), F("createdAt", "Timestamp", computed)],
      },
    ],
  },
  {
    id: "euromecc-ordine-ricambi",
    modal: "NextEuromeccPage (ordine ricambi da relazione)",
    component: "NextEuromeccPage",
    file: "src/next/NextEuromeccPage.tsx",
    operations: ["create"],
    writes: [
      {
        path: "storage/@ordini",
        kind: "storageDoc",
        operation: "setDoc storage doc value[]",
        evidence: [{ file: "src/next/NextEuromeccPage.tsx", pattern: "async function handleCreaOrdineRicambiAndSave" }],
        fields: [F("id", "string", computed), F("idFornitore", "string", defaulted), F("nomeFornitore", "string", form), F("dataOrdine", "string", form), F("materiali", "array<object>", ia), F("arrivato", "boolean", defaulted)],
      },
      {
        path: "euromecc_relazioni",
        kind: "collection",
        operation: "addDoc relazione importata",
        evidence: [{ file: "src/next/NextEuromeccPage.tsx", pattern: "ordineId," }],
        fields: [F("ordineId", "string", computed), F("ordineMateriali", "number", computed), F("statoImportazione", "string", defaulted), F("note", "string", computed)],
      },
    ],
  },
  {
    id: "euromecc-pending",
    modal: "NextEuromeccPage (task da fare)",
    component: "NextEuromeccPage",
    file: "src/next/NextEuromeccPage.tsx",
    operations: ["create", "update", "delete"],
    writes: [
      {
        path: "euromecc_pending",
        kind: "collection",
        operation: "addDoc/updateDoc/deleteDoc",
        evidence: [{ file: "src/next/domain/nextEuromeccDomain.ts", pattern: "export async function addEuromeccPendingTask" }],
        fields: [F("areaKey", "string", prop), F("subKey", "string", prop), F("title", "string", form), F("priority", "string", form), F("dueDate", "string", form), F("note", "string", form), F("createdAt", "Timestamp", computed), F("updatedAt", "Timestamp", computed)],
      },
    ],
  },
  {
    id: "euromecc-done",
    modal: "NextEuromeccPage (task fatto)",
    component: "NextEuromeccPage",
    file: "src/next/NextEuromeccPage.tsx",
    operations: ["create", "update", "delete"],
    writes: [
      {
        path: "euromecc_done",
        kind: "collection",
        operation: "addDoc/updateDoc/deleteDoc",
        evidence: [{ file: "src/next/domain/nextEuromeccDomain.ts", pattern: "export async function addEuromeccDoneTask" }],
        fields: [F("areaKey", "string", prop), F("subKey", "string", prop), F("title", "string", form), F("doneDate", "string", form), F("by", "string", form), F("note", "string", form), F("nextDate", "string|null", form), F("closedPending", "boolean", form), F("createdAt", "Timestamp", computed), F("updatedAt", "Timestamp", computed)],
      },
    ],
  },
  {
    id: "euromecc-issue",
    modal: "NextEuromeccPage (segnalazione)",
    component: "NextEuromeccPage",
    file: "src/next/NextEuromeccPage.tsx",
    operations: ["create", "update", "delete"],
    writes: [
      {
        path: "euromecc_issues",
        kind: "collection",
        operation: "addDoc/updateDoc/deleteDoc",
        evidence: [{ file: "src/next/domain/nextEuromeccDomain.ts", pattern: "export async function addEuromeccIssue" }],
        fields: [F("areaKey", "string", prop), F("subKey", "string", prop), F("title", "string", form), F("check", "string", form), F("type", "string", form), F("state", "string", form), F("reportedAt", "string", form), F("reportedBy", "string", form), F("note", "string", form), F("closedDate", "string|null", form), F("createdAt", "Timestamp", computed), F("updatedAt", "Timestamp", computed)],
      },
    ],
  },
  {
    id: "euromecc-cement-type",
    modal: "NextEuromeccPage (tipo cemento silo)",
    component: "NextEuromeccPage",
    file: "src/next/NextEuromeccPage.tsx",
    operations: ["update"],
    writes: [
      {
        path: "euromecc_area_meta",
        kind: "collection",
        operation: "setDoc area meta",
        evidence: [{ file: "src/next/domain/nextEuromeccDomain.ts", pattern: "saveEuromeccAreaCementType" }],
        fields: [F("areaKey", "string", prop), F("cementType", "string", form), F("cementTypeShort", "string", form), F("updatedBy", "string", form), F("updatedAt", "Timestamp", computed)],
      },
    ],
  },
];

export const TOOL_MAPPINGS = {
  "storage/@colleghi": {
    tools: ["list_drivers", "get_driver_by_name", "get_driver_by_badge", "get_driver_operational_profile"],
    reader: "readNextColleghiSnapshot",
    fieldsRead: ["id", "nome", "telefono", "telefonoPrivato", "badge", "descrizione", "codice", "pinSim", "pukSim", "schedeCarburante"],
    notes: ["get_driver_by_name e get_driver_by_badge restituiscono item/matches del domain item completo."],
  },
  "storage/@fornitori": {
    tools: ["list_suppliers", "get_procurement_costs"],
    reader: "readNextFornitoriSnapshot + readNextProcurementSnapshot",
    fieldsRead: ["id", "nome", "telefono", "badge", "codice", "descrizione"],
  },
  "storage/@officine": {
    tools: ["list_workshops"],
    reader: "readNextOfficineSnapshot",
    fieldsRead: ["id", "nome", "telefono", "telefoniAggiuntivi", "citta"],
  },
  "storage/@mezzi_aziendali": {
    tools: ["list_vehicles", "get_vehicle_by_plate", "search_vehicles_by_attribute", "get_vehicle_status", "list_scheduled_maintenance_due", "get_vehicle_dossier_snapshot"],
    reader: "readNextAnagraficheFlottaSnapshot/readNextMezzoByTarga/readNextCentroControlloSnapshot",
    fieldsRead: ["id", "tipo", "categoria", "anno", "targa", "marca", "modello", "marcaModello", "telaio", "colore", "cilindrata", "potenza", "massaComplessiva", "proprietario", "assicurazione", "dataImmatricolazione", "dataScadenzaRevisione", "dataUltimoCollaudo", "manutenzioneProgrammata", "manutenzioneDataInizio", "manutenzioneDataFine", "manutenzioneKmMax", "manutenzioneContratto", "note", "autistaId", "autistaNome", "fotoUrl", "fotoPath", "librettoUrl", "librettoStoragePath", "libretto_raw", "prenotazioneCollaudo", "preCollaudo"],
    filterGaps: ["list_vehicles filtra categoria su categoria/tipo normalizzati; valori non canonici restano leggibili da get_vehicle_by_plate ma possono non uscire dalla lista filtrata."],
  },
  "storage/@preventivi": {
    tools: ["get_procurement_costs", "list_suppliers"],
    reader: "readNextProcurementSnapshot/readNextProcurementReadOnlySnapshot",
    fieldsRead: ["id", "fonte", "fornitoreId", "fornitoreNome", "numeroPreventivo", "dataPreventivo", "righe", "valuta", "imageStoragePaths", "imageUrls", "pdfStoragePath", "pdfUrl", "createdAt", "updatedAt"],
  },
  "storage/@listino_prezzi": {
    tools: ["get_procurement_costs", "list_suppliers"],
    reader: "readNextProcurementSnapshot/readNextProcurementReadOnlySnapshot",
    fieldsRead: ["id", "fornitoreId", "fornitoreNome", "articoloCanonico", "codiceArticolo", "unita", "prezzoAttuale", "valuta", "preventivoId", "updatedAt"],
  },
  "chat_ia_reports": {
    tools: ["list_archived_reports", "retrieve_archived_report", "save_report_to_archive", "delete_archived_report"],
    reader: "readChatIaReportArchive/readChatIaReportArchiveEntry",
    fieldsRead: ["version", "status", "prompt", "title", "sector", "targetKind", "targetValue", "periodFrom", "periodTo", "summary", "blocks", "pdfUrl", "pdfStoragePath", "createdAt", "updatedAt", "meta", "deletedAt"],
  },
  "storage/@attrezzature_cantieri": {
    tools: ["get_site_equipment"],
    reader: "readNextAttrezzatureCantieriSnapshot",
    fieldsRead: ["id", "tipo", "data", "timestamp", "materialeCategoria", "descrizione", "quantita", "unita", "cantiereId", "cantiereLabel", "note", "fotoUrl", "fotoStoragePath", "sourceCantiereId", "sourceCantiereLabel"],
  },
  "storage/@manutenzioni": {
    tools: ["get_vehicle_maintenance_history", "search_maintenances", "list_scheduled_maintenance_due", "get_vehicle_timeline_360", "get_vehicle_dossier_snapshot"],
    reader: "readNextMezzoManutenzioniSnapshot/readNextManutenzioniGlobale",
    fieldsRead: ["id", "targa", "tipo", "fornitore", "km", "ore", "sottotipo", "descrizione", "eseguito", "data", "materiali", "importo", "gommeInterventoTipo", "gommeStraordinario", "assiCoinvolti", "gommePerAsse", "sourceDocumentId"],
  },
  "storage/@inventario": {
    tools: ["list_inventory"],
    reader: "readNextInventarioSnapshot",
    fieldsRead: ["id", "descrizione", "quantita", "quantitaTotale", "unita", "stockKey", "stockLoadKeys", "fotoUrl", "fotoStoragePath", "fornitore", "fornitoreLabel", "nomeFornitore", "sogliaMinima"],
  },
  "storage/@materialiconsegnati": {
    tools: ["get_material_movements", "get_vehicle_material_movements", "get_vehicle_dossier_snapshot"],
    reader: "readNextMaterialiMovimentiSnapshot",
    fieldsRead: ["id", "tipo", "direzione", "data", "materialeId", "inventarioRefId", "materialeLabel", "materiale", "descrizione", "quantita", "unita", "origine", "targa", "mezzoTarga", "fornitore", "fornitoreLabel", "stockKey", "destinatario", "target", "motivo"],
  },
  "storage/@lavori": {
    tools: ["search_work_orders", "get_vehicle_timeline_360", "get_vehicle_dossier_snapshot"],
    reader: "readNextLavoriSnapshot/readChatIaMezzoSnapshot",
    fieldsRead: ["id", "gruppoId", "tipo", "targa", "descrizione", "dataInserimento", "eseguito", "urgenza", "segnalatoDa", "sottoElementi", "chiHaEseguito", "dataEsecuzione"],
  },
  "storage/@mezzi_foto_viste": {
    tools: [],
    reader: null,
    fieldsRead: [],
  },
  "storage/@mezzi_hotspot_mapping": {
    tools: [],
    reader: null,
    fieldsRead: [],
  },
  "storage/@cisterne_adblue": {
    tools: ["get_adblue_tank_events", "get_material_movements"],
    reader: "readNextMaterialiMovimentiSnapshot/readNextAdBlueSnapshot",
    fieldsRead: ["id", "data", "quantitaLitri", "quantita", "litri", "inventarioRefId", "stockKey", "materialeLabel", "descrizione", "unita", "numeroCisterna", "note"],
  },
  "storage/@ordini": {
    tools: ["get_procurement_costs", "list_suppliers"],
    reader: "readNextProcurementSnapshot/readNextProcurementReadOnlySnapshot",
    fieldsRead: ["id", "idFornitore", "nomeFornitore", "dataOrdine", "materiali", "arrivato", "ordineNote", "materiali[].id", "materiali[].descrizione", "materiali[].quantita", "materiali[].unita", "materiali[].arrivato", "materiali[].dataArrivo", "materiali[].fotoUrl", "materiali[].fotoStoragePath", "materiali[].note", "materiali[].prezzoUnitario", "materiali[].valuta", "materiali[].unitaPrezzo"],
  },
  "@documenti_mezzi": {
    tools: ["search_documents_and_invoices", "get_document_costs_by_vehicle", "get_vehicle_documents", "get_invoice_by_id", "find_invoice_supplier", "download_document_pdf"],
    reader: "nextDocumentiCostiDomain/nextDocumentiMezzoDomain",
    fieldsRead: ["id", "sourceDocId", "currency", "valuta", "fileUrl", "storagePath", "targa", "tipoDocumento", "numeroDocumento", "dataDocumento", "totaleDocumento", "fornitore"],
  },
  "@documenti_magazzino": {
    tools: ["search_documents_and_invoices", "get_document_costs_by_vehicle", "get_vehicle_documents", "get_invoice_by_id", "find_invoice_supplier", "download_document_pdf"],
    reader: "nextDocumentiCostiDomain/nextDocumentiMezzoDomain",
    fieldsRead: ["id", "sourceDocId", "currency", "valuta", "fileUrl", "storagePath", "targa", "tipoDocumento", "numeroDocumento", "dataDocumento", "totaleDocumento", "fornitore", "voci"],
  },
  "@documenti_generici": {
    tools: ["search_documents_and_invoices", "get_document_costs_by_vehicle", "get_vehicle_documents", "get_invoice_by_id", "find_invoice_supplier", "download_document_pdf"],
    reader: "nextDocumentiCostiDomain/nextDocumentiMezzoDomain",
    fieldsRead: ["id", "sourceDocId", "currency", "valuta", "fileUrl", "storagePath", "targa", "tipoDocumento", "numeroDocumento", "dataDocumento", "totaleDocumento", "fornitore"],
  },
  "storage/@costiMezzo": {
    tools: ["get_costs", "get_cost_aggregates", "get_document_costs_by_vehicle", "get_vehicle_cost_summary"],
    reader: "nextDocumentiCostiDomain",
    fieldsRead: ["id", "sourceDocId", "currency", "valuta", "targa", "tipo", "data", "importo", "fornitore", "descrizione"],
  },
  "@cisterna_parametri_mensili": {
    tools: ["get_cisterna_snapshot", "reconcile_cisterna_month"],
    reader: "readNextCisternaSnapshot",
    fieldsRead: ["mese", "cambioEurChf", "updatedAt"],
  },
  "@documenti_cisterna": {
    tools: ["get_cisterna_snapshot", "get_cisterna_documents", "reconcile_cisterna_month"],
    reader: "readNextCisternaSnapshot",
    fieldsRead: ["id", "tipoDocumento", "fornitore", "destinatario", "numeroDocumento", "dataDocumento", "yearMonth", "mese", "litriTotali", "litri15C", "totaleDocumento", "valuta", "currency", "prodotto", "testo", "daVerificare", "motivoVerifica", "fileUrl", "storagePath", "nomeFile", "fonte", "createdAt", "iaEngine", "dupGroupKey", "dupChosen", "dupIgnored", "updatedAt"],
  },
  "@cisterna_schede_ia": {
    tools: ["get_cisterna_snapshot", "get_cisterna_refuelings", "reconcile_cisterna_month"],
    reader: "readNextCisternaSnapshot",
    fieldsRead: ["id", "source", "rowCount", "rows", "needsReview", "yearMonth", "fileUrl", "storagePath", "nomeFile", "rawLines", "summary", "fonte", "iaEngine", "createdAt", "updatedAt"],
  },
  "euromecc_pending": {
    tools: ["get_euromecc_snapshot"],
    reader: "readEuromeccSnapshot",
    fieldsRead: ["id", "areaKey", "subKey", "title", "priority", "dueDate", "note", "createdAt", "updatedAt", "areaLabel", "state"],
  },
  "euromecc_done": {
    tools: ["get_euromecc_snapshot"],
    reader: "readEuromeccSnapshot",
    fieldsRead: ["id", "areaKey", "subKey", "title", "doneDate", "by", "note", "nextDate", "closedPending", "createdAt", "updatedAt", "areaLabel", "state"],
  },
  "euromecc_issues": {
    tools: ["get_euromecc_snapshot"],
    reader: "readEuromeccSnapshot",
    fieldsRead: ["id", "areaKey", "subKey", "title", "check", "type", "state", "reportedAt", "reportedBy", "note", "closedDate", "createdAt", "updatedAt", "areaLabel"],
  },
  "euromecc_area_meta": {
    tools: ["get_euromecc_snapshot"],
    reader: "readEuromeccSnapshot",
    fieldsRead: ["areaKey", "cementType", "cementTypeShort", "updatedBy", "updatedAt"],
  },
  "euromecc_relazioni": {
    tools: [],
    reader: null,
    fieldsRead: [],
  },
  "euromecc_extra_components": {
    tools: [],
    reader: null,
    fieldsRead: [],
  },
};

export const CATEGORICAL_FIELDS_BY_PATH = {
  "storage/@colleghi": ["badge", "codice"],
  "storage/@fornitori": ["nome"],
  "storage/@officine": ["citta"],
  "storage/@mezzi_aziendali": ["tipo", "categoria", "manutenzioneProgrammata"],
  "storage/@preventivi": ["fonte", "fornitoreNome", "valuta"],
  "storage/@listino_prezzi": ["fornitoreNome", "valuta", "unita"],
  "chat_ia_reports": ["status", "sector", "targetKind"],
  "storage/@attrezzature_cantieri": ["tipo", "materialeCategoria", "cantiereLabel"],
  "storage/@manutenzioni": ["tipo", "sottotipo", "eseguito", "gommeInterventoTipo"],
  "storage/@inventario": ["unita", "fornitore"],
  "storage/@materialiconsegnati": ["tipo", "direzione", "origine", "targa"],
  "storage/@lavori": ["tipo", "urgenza", "eseguito", "segnalatoDa"],
  "storage/@cisterne_adblue": ["numeroCisterna"],
  "storage/@ordini": ["nomeFornitore", "arrivato"],
  "@documenti_mezzi": ["tipoDocumento", "currency", "valuta"],
  "@documenti_magazzino": ["tipoDocumento", "currency", "valuta"],
  "@documenti_generici": ["tipoDocumento", "currency", "valuta"],
  "storage/@costiMezzo": ["tipo", "currency", "valuta"],
  "@cisterna_parametri_mensili": ["mese"],
  "@documenti_cisterna": ["tipoDocumento", "fornitore", "valuta", "currency", "fonte", "dupChosen", "dupIgnored"],
  "@cisterna_schede_ia": ["source", "fonte", "needsReview", "yearMonth"],
  "euromecc_pending": ["areaKey", "priority"],
  "euromecc_done": ["areaKey", "closedPending"],
  "euromecc_issues": ["areaKey", "type", "state"],
  "euromecc_area_meta": ["areaKey"],
  "euromecc_relazioni": ["fileType", "statoImportazione"],
  "euromecc_extra_components": ["areaKey"],
};
